### ISSUE TITLE
Implement direct messages

### ISSUE THREAD

**Issue by robertodoering** [robertodoering/harpy#130]
The user should be able to send and see his direct messages.

**Comment by monee121** [comment]
Hi, yes DM support is a must have for me and I hope it comes with 1.0.  I think it should have it's own tab like Home, mentions, etc and be able to be reordered on the toolbar.

**Comment by dnestico** [comment]
👀 https://trello.com/c/TRkr2XsM/74-replacement-for-direct-message-functionality

**Comment by Varpie** [comment]
With the mass extinction of Twitter third-party clients, Harpy seems to be the only viable option left... But it still does not have DMs, which I consider essential. Since DMs are now part of the v2 API, will this feature be re-prioritized?

**Comment by robertodoering** [comment]
No, read #884
