### ISSUE TITLE
Sometimes tweets wont get tweeted

### ISSUE THREAD

**Issue by nikolajjsj** [robertodoering/harpy#207]
When is use the API to update (create) a tweet, it will sometimes get an error response:
Status code:401
{"errors":[{"code":32,"message":"Could not authenticate you."}]}, 
reason: Authorization Required

But only sometimes, so often it does not occur

**Comment by robertodoering** [comment]
Is this issue meant to be on https://github.com/robertodoering/twitter_api?
Tweeting hasn't been implemented in harpy yet

**Comment by nikolajjsj** [comment]
Yes it is sorry.. I've been coding for hours so my brain is almost done..

**Comment by robertodoering** [comment]
👍 Thanks for reporting it either way
Ill close it here and add a new issue in https://github.com/robertodoering/twitter_api 😃
