### ISSUE TITLE
Go edge-to-edge

### ISSUE THREAD

**Issue by cccClyde** [robertodoering/harpy#247]
Harpy is clean and elegant and it will be nice to have edge-to-edge implementation.

See: [Going edge-to-edge with Gesture Navigation](https://chris.banes.dev/going-edge-to-edge-ads/)

**Comment by robertodoering** [comment]
Hi @cccClyde,
what are you looking for when you mention an edge-to-edge implementation?

Edge-to-edge gesture navigation is part of Android 10+, so you need to enable it in your settings if you want to be able to use it.
The app itself doesn't have to do anything in particular to support it.

However I wasn't aware that the app can draw behind the status and navigation bar. I have experimented and it looks great!
Is this what you were looking for?

Here is what it looks like:

| gesture navigation | 3 button navigation |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/20045287/104424023-1c5d0d80-557f-11eb-8a9a-8fb93c54a7da.png" width="400" /> | <img src="https://user-images.githubusercontent.com/20045287/104424020-1b2be080-557f-11eb-956c-b06299e60fb7.png" width="400" /> |

**Comment by cccClyde** [comment]
Oh sorry for not being transparent. I was talking about [transparent system bars](https://developer.android.com/training/gestures/gesturenav#transparent-bars), specifically nav bar which is now opaque. Your experiment achieved exactly what I was asking about.

Looking forward to the final implementation, and also Harpy Pro. Thanks for your work!

**Comment by robertodoering** [comment]
Awesome! Thanks for showing me, it looks great!
You can expect in the the release following the next one (0.3.4)
