### ISSUE TITLE
Support for multiple accounts

### ISSUE THREAD

**Issue by robertodoering** [robertodoering/harpy#249]
* Quick switch between multiple accounts
* Maybe an optional shared timeline

**Comment by Tdoscar** [comment]
I would like to know when this function can be released? Thank you very much!

**Comment by i4mnonexistent** [comment]
If I can add and switch multi-accounts, I'd buy this app though. When would you add this function?

**Comment by lewdnasty** [comment]
Chiming in to say I would love this feature as well. Would absolutely drop a couple bucks to support if this could get added. Literally the only thing preventing me from converting to this app exclusively.

**Comment by HikaruIchijyo** [comment]
what about simple quick account switch rest can be done later cuz this is most needed feature as of right now

**Comment by famin3pulse** [comment]
Greetings rebertodoering. Thank you for making a terrific app. I've purchased the pro version and really appreciate your work. Whenever you get around to it, account switching would be helpful. Thank you.
