### ISSUE TITLE
Add opening Twitter & Tweet links through harpy

### ISSUE THREAD

**Issue by robertodoering** [robertodoering/harpy#256]
When opening a tweet url outside of harpy, harpy should be able to open and show the tweet.

Additionally, when tapping a twitter url inside of harpy, the user shouldn't navigate out of harpy.

**Comment by sheeepdev** [comment]
Hey, I know this is planned, but any Twitter app should have this from the beginning... I normally use Twitter from clicking on links, but Harpy doesn't have this function..

**Comment by robertodoering** [comment]
@sheeepdev I don't share your opinion and won't prioritize this feature as I believe there are more important issues to work on first. However, if you are interested in contributing to the project feel free to implement this yourself and open a PR whenever you like :)

**Comment by sheeepdev** [comment]
> @sheeepdev I don't share your opinion and won't prioritize this feature as I believe there are more important issues to work on first. However, if you are interested in contributing to the project feel free to implement this yourself and open a PR whenever you like :)

I'm so sorry if I sounded angry or something, I just thought its an important feature, but I respect that you don't share the same opinion as me, I will wait until you implement this :)

**Comment by robertodoering** [comment]
No worries, thanks for letting me know about your interest in this feature.
For now I plan to work on other issues first that are more important for me but down the line you can expect this feature to make it into Harpy :)

**Comment by robertodoering** [comment]
Will be implemented after #481

**Comment by sheeepdev** [comment]
:o

**Comment by Slusho64** [comment]
I'd just like to give some feedback that I, too, need link handling in order for a Twitter client to be useful because 95% of my use is through links. I wish I could help.
