### ISSUE TITLE
Open links in a webview inside the app

### ISSUE THREAD

**Issue by robertodoering** [robertodoering/harpy#268]
The user will be able to open the link externally if they want to.

If the `Settings > Media > Always open externally` is enabled, links will never be opened inside a web view.

**Comment by dnestico** [comment]
Hope this comes next!

**Comment by natediz** [comment]
Hey, in addition to this, could you have an option for Twitter links to other tweets etc to open internally in the app rather than the official website?

**Comment by dnestico** [comment]
> Hey, in addition to this, could you have an option for Twitter links to other tweets etc to open internally in the app rather than the official website?

Was just about to come suggest this too!
