### ISSUE TITLE
Reduce swipe to refresh sensitivity

### ISSUE THREAD

**Issue by armandojrod** [robertodoering/harpy#287]
It takes as start the top of the display so you have to swipe longer than normal on a tall phone, the swipe should start from the app toolbar not the top of the display

**Comment by scottiefalkon** [comment]
Along with this issue, Refresh doesn't seem to be working at all since latest release. From a swipe down or from the button.

**Comment by darrenmcentee** [comment]
> Along with this issue, Refresh doesn't seem to be working at all since the latest release. From a swipe down or from the button.

Yeah, I noticed the same thing. Thought it was my connection. But I think the new filters feature may be interfering with the timeline, even when filters are off. Seems to infinitely refresh.

**Comment by robertodoering** [comment]
Refreshing in the home timeline broke with update 0.4.4. A fix is currently in review and will be published in the play store in the next 48 hours.

I agree the refresh swipe is annoyingly long. There isn't an easy way to adjust the sensitivity of it but I will experiment with it soon.
The position or display size doesn't have anything to do with it's sensitivity, but I agree it should start below the app bar.

**Comment by robertodoering** [comment]
I made it easier to trigger the refresh (basically you have to swipe down less to move the refresh indicator farther). I also displaced the indicator below the app bar.
Both will be in the next version (0.4.6)

Thanks for the suggestions!
