### ISSUE TITLE
Add toggle to show absolute time of tweet

### ISSUE THREAD

**Issue by robertodoering** [robertodoering/harpy#301]
~~Maybe as part of the tweet card content customization #304~~
For now as a separate option.

#### Description:
Currently the tweet card shows a relative time of tweet creation next to the handle of the tweet author.

Instead the user should be able to see the time of creation if they want to.

e.g.: `@username · 3 hours ago`
should be `@username · 7/29/2021 4:20 PM`

The toggle can be placed in the display settings.

##### Tweet card date display
The for a tweet card is created in `TweetCardHandle` in the `_CreatedAtTime`. When the option is enabled, instead of building a `_CreatedAtTime` we can build a different widget which builds the absolute time text.
Make sure the text also applies the size delta from the configuration.

Here is an example of a localized date format which can be used.
```dart
DateFormat.yMd(Localizations.localeOf(context).languageCode)
    .add_Hm()
    .format(tweet.createdAt.toLocal())
    .toLowerCase();
```
It might be worth removing the year if the tweet is of the current year.

##### Toggle
Since the tweet card handle needs to rebuild when the user toggles the new setting, we need to add a new field in the `Config` and update it in the `ConfigCubit`.

- E.g. add field `showAbsoluteTime` in `Config` (defaults to false)
- add `updateShowAbsoluteTime` in `ConfigCubit` which saves the option in the preferences and updates the config
- load the preference value in `initialize` in the `ConfigCubit`

Note: Using the `Config` here for the field is only temporary and will be replaced with a field in the `TweetCardConfig` once the tweet card configuration is built (#304)

**Comment by borisgrigorov** [comment]
Hello, I would like to contribute to this project. I don't promise anything, but can I take a look at this?

**Comment by robertodoering** [comment]
Hey @borisgrigorov, yes absolutely!

I will update the ticket to give a bit more information of what the requirements are.


Here is some information for setting up the project to start development,
if you have any questions let me know.

- be on the flutter stable channel
- get a twitter api key and set it up:
  - change the permissions to allow (at least) read + write access
  - enable 3 legged oauth and set the callback url to `harpy://`
  - run the project with the twitter key & secret and the android flavor `free` or `pro`:
    -  `flutter run --flavor free --dart-define=flavor=free --dart-define=twitter_consumer_key=your_consumer_key --dart-define=twitter_consumer_secret=your_consumer_secret`
    - here is an example of a launch configuration if you use vscode:
       ```
        {
            "name": "harpy free debug",
            "request": "launch",
            "type": "dart",
            "flutterMode": "debug",
            "args": [
                "--flavor",
                "free",
                "--dart-define=flavor=free",
                "--dart-define=twitter_consumer_key=abcdef",
                "--dart-define=twitter_consumer_secret=abcdef"
            ]
        },```

Example twitter api key configuration:
![image](https://user-images.githubusercontent.com/20045287/127531729-409f2e74-4125-42a2-933c-320183ec0b68.png)

**Comment by pedr0luiz** [comment]
I can fix this.

**Comment by robertodoering** [comment]
Go for it!

**Comment by pedr0luiz** [comment]
Hi! I've created the field showAbsoluteTime in Config and updateShowAbsoluteTime in ConfigCubit, but I'm facing some state management problems. The field is only updated when I reload the app. Can you help me if I open a draft PR?

Uploading Screen Recording 2021-11-10 at 12.37.33.mov…
