### ISSUE TITLE
Add ability to toggle immersive mode

### ISSUE THREAD

**Issue by corylowry12** [robertodoering/harpy#320]
Give the ability to toggle immersive mode where the status bar doesnt go transparent when scrolling.

**Comment by robertodoering** [comment]
Right now the status bar and navigation bar is always transparent.
I agree that someone might not want that. I added customization for the status bar color as a requirement in #282.
I also might make it slightly less translucent for the default themes.

With that you can customize the status bar color and make it opaque if you want to.
