### ISSUE TITLE
Migrate to Twitter API v2

### ISSUE THREAD

**Issue by robertodoering** [robertodoering/harpy#322]
The new Twitter API is still in development but we can already migrate the existing endpoints (timelines, user profile, etc.)

This includes the ability to add some functionality that is not available for the current v1.1 API:
- show reply count
- show polls
- etc.

**Comment by dnestico** [comment]
Nice! 👀 https://twitter.com/TwitterDev/status/1460323737035677698?t=DfvgJNXujHV8agx6oFk_DQ

**Comment by monee121** [comment]
Is it possible to view any user's mentions? I do like that feature on some apps.

**Comment by robertodoering** [comment]
>Is it possible to view any user's mentions? I do like that feature on some apps.

You can search for @username in the tweet search to get any user's mentions

**Comment by rzlamrr** [comment]
I hope harpy can migrate to twitter api v2 endpoint soon 😅

**Comment by VexfulNiko** [comment]
@robertodoering Whats if any is blocking a migration to v2?

**Comment by robertodoering** [comment]
@VexfulNiko It's not blocked

**Comment by VexfulNiko** [comment]
@robertodoering What's preventing you from updating the API, if you don't mind me asking?

**Comment by dnestico** [comment]
Probably the amount time it will take. No rush!

**Comment by robertodoering** [comment]
I haven't had much time to work on harpy recently, hopefully I can dedicate more time to it in the future but I also have a lot of other responsibilities so it's always hard to tell
