### ISSUE TITLE
Keep timeline position when refreshing Tweets

### ISSUE THREAD

**Issue by robertodoering** [robertodoering/harpy#323]
When updating the timeline, the scroll position should not change and instead the user should be able to scroll up to read the new tweets.

**Comment by clambert11** [comment]
This is important to me too. Hopefully it can be added at some point.

**Comment by AmjadAGA** [comment]
Still not working in the last Verizon

**Comment by CaptainBeaky76** [comment]
+1 for this, is a must have for me to start using this app exclusively. Is this still on the cards after 1.0?

**Comment by armandojrod** [comment]
Why exactly this feature is marked as "expensive" or "brings uncertainty" it is because of the programming language? Serious question.

IMHO this should be a basic feature

**Comment by S3basuchian** [comment]
This is the one feature that really keeps me from using harpy exclusively. Hoping it will be implemented soon!

**Comment by S3basuchian** [comment]
Done in #821 :)

**Comment by dnestico** [comment]
SWEET! Nice 👍
