### ISSUE TITLE
Fix webview login 2FA callback

### ISSUE THREAD

**Issue by tgperales** [robertodoering/harpy#332]
After updating to 0.5.4, i can't seem to get pass the authorization part after being redirected to the phone browser. I tried using Bromite, Brave and the built-in browser but nothing seems to be working. It looks like it was suppose to redirect the URL link with the auth token (harpy://?auth_token=xxxxxxxxxxx) to the Harpy app but for some reason it cannot get it. Hope i can get a solution for this

**Comment by robertodoering** [comment]
Are you using 2FA to log in with Twitter?
I think there is an issue where the callback when 2FA is in use is not handled properly.

I have an update rolling out right now that re-adds the legacy login for users that have issues with the webview login.

**Comment by tgperales** [comment]
Yes i have 2FA set up on my account. Seems that was the problem. 

Looking forward to the update
