### ISSUE TITLE
Character limit counter

### ISSUE THREAD

**Issue by neillium** [robertodoering/harpy#334]
I've looked all over for this feature. Unless I am missing it somewhere, having some sort of count where I can see how many characters I have left when typing would be great! Having to guess when I hit the limit and how much I need to delete can be frustrating.

**Comment by robertodoering** [comment]
Sounds good!
The implementation is not as straight forward as counting each character or code point, but it shouldn't be too difficult to add.

https://developer.twitter.com/en/docs/counting-characters
