### ISSUE TITLE
Add option the view the best image quality in the app

### ISSUE THREAD

**Issue by robertodoering** [robertodoering/harpy#335]
Beta 0.5.4 improved the performance for low end devices partially by always using the small media images in the app.

Users for whom the performance impact is negligible should still be able to view the best quality images in the app by toggling an option in the media settings.
`Use higher image quality: on / off` 

This option will be `off` by default but will be added to the setup screen.

The `download image` / `share image` / `open image externally` url is not affected by this and will always default to the best image quality available.

**Comment by robertodoering** [comment]
@dnestico this will re-add the ability for users to view the best quality images in the app, like you suggested!

**Comment by dnestico** [comment]
Nice!
