### ISSUE TITLE
Improve navigation with horizontal swipe gesture

### ISSUE THREAD

**Issue by robertodoering** [robertodoering/harpy#340]
The user should be able to swipe horizontally to pop the navigator or to open the home drawer.
The same way the Cupertino page route can pop the screen when swiping on the edge, but on the whole screen.

When the screen contains horizontal scrolling gestures (e.g. the home screen), the screen level scrolling should take precedence.

**Comment by xiprox** [comment]
I'd like to voice an opinion against this. On many apps that implement this navigation gesture, I find myself often accidentally navigating back and it's extremely frustrating, and I doubt I am the only one. This is probably the reason why Apple's gesture only triggers from the edge.

**Comment by robertodoering** [comment]
I can see that this isn't for everyone. I will experiment with it and if it works for me I will at least make it optional.
Thanks for your input :)
