### ISSUE TITLE
Add double-tap-and-drag gesture for image zooming

### ISSUE THREAD

**Issue by ripdog** [robertodoering/harpy#344]
Hi there, thanks for Harpy! It's great.

One really nice feature that I miss for single handed use is the ability to use the classic Android gesture double-tap-and-drag to zoom images. Having to use a second hand anytime I want to zoom an image is a little annoying.

Looking forward to the opportunity to buy Pro :) thanks!

**Comment by robertodoering** [comment]
Thanks @ripdog :)

By `double-tap-and-drag` gesture, do you mean you want to double-tap and then be able to drag around the image without having to lift your finger?
You can already double tap and then drag afterwards (that should be the same behavior as in the Twitter app or in the image viewer from Google Photos)

**Comment by ripdog** [comment]
Double-tap-and-drag is the original Android zoom gesture, it was
implemented before pinch-zoom. (I believe there was some kind of software
patent on pinch-zoom at the beginning).

Try it on Google Photos or most other Android apps with photos you can
zoom. Using a single finger, double tap, but leave your finger on the
screen after the second tap. The drag finger up and down to zoom the image
in and out.

Just testing now, I discovered that the official twitter app doesn't
support this?! Instead it just zooms to a fixed level on double tap. I
never noticed because that's all I want 😂
But most Android apps support the full gesture, and it'd be nice here if
possible. Thanks.

**Comment by robertodoering** [comment]
Ah, thanks for clarifying! I've never used that feature before and didn't even know about it :D

I can add that in the future :) thanks for the request!
