### ISSUE TITLE
Auto-pause videos when off screen

### ISSUE THREAD

**Issue by ripdog** [robertodoering/harpy#345]
Currently, when I unmute a video and scroll it off screen, it continues playing to the end even though I can't access the media controls. This is a little annoying! 

Understanding that some people might want to continue listening to videos while they scroll, I think there are two solutions. One is to have a global preference for 'continue playing unmuted videos when off screen', but perhaps a better solution is to add a new button to the video player which causes it to pop out into a floating window, so it can still be watched and paused later.

Anyway, thank you again.

**Comment by robertodoering** [comment]
Thanks for the issue!

I like the idea of a picture-in-picture viewer for videos :)
I will change it so that videos get muted as soon as they are scrolled off screen and add the pop out floating video viewer separately in the future.
