### ISSUE TITLE
Add search screen navigation in drawer

### ISSUE THREAD

**Issue by robertodoering** [robertodoering/harpy#349]
Since the search tab in the home screen can be hidden (pro only).

- Wrap the current search screen in a scaffold (in a new widget)
- Add list tile in home drawer

**Comment by eRuaro** [comment]
Hi! I'd like to take this issue, do I work on the pro version of the app or the standard version?

**Comment by robertodoering** [comment]
Hey, sounds good! The free and pro version uses the same code base so there is no differentiation. I would make the search screen button visible in both versions.
If you need help with anything let me know :)

**Comment by eRuaro** [comment]
Hey! About to start working on this now, how do I add ```flutter run --flavor pro --dart-define=flavor=pro --dart-define=twitter_consumer_key=your_consumer_key --dart-define=twitter_consumer_secret=your_consumer_secret``` into a ```launch.json``` file?

**Comment by robertodoering** [comment]
A launch configuration for vscode looks like this:
```
{
    "name": "harpy free debug",
    "request": "launch",
    "type": "dart",
    "flutterMode": "debug",
    "args": [
        "--flavor",
        "free",
        "--dart-define=flavor=free",
        "--dart-define=twitter_consumer_key=abcdef",
        "--dart-define=twitter_consumer_secret=abcdef"
    ]
},
```

**Comment by eRuaro** [comment]
Awesome, thanks!

**Comment by eRuaro** [comment]
Hey! How do I fix this? 
```
+++
No keystore defined. The app will not be signed.
Create a android/key.properties file with the following properties:
storePassword
keyPassword
keyAlias
storeFile
+++

```

**Comment by eRuaro** [comment]
The app still ran with the error above, but I'm having authentication issues when I press the ```login with twitter``` button on the log in screen

**Comment by robertodoering** [comment]
You can ignore the keystore warning.
Have you put in your own api key?

**Comment by eRuaro** [comment]
Yep, I've included in my own api keys!  Specifically I included the consumer keys. Are there any settings I need to tweak on the twitter developers app dashboard?

**Comment by robertodoering** [comment]
Ah, yes, you will need to set the app permissions, enable 3-legged oauth authentication and add harpy:// as a callback uri in the settings:
![image](https://user-images.githubusercontent.com/20045287/123759451-35087800-d8c0-11eb-8862-65f20da21214.png)

(I really should write a setup guide in the future, sorry!)


With that you should be able to authenticate with your api key and use the app without issues, if there is anything else that pops up let me know

**Comment by eRuaro** [comment]
Okay got that! What should I type in the `website url`?

**Comment by robertodoering** [comment]
The `website url` field doesn't matter

**Comment by eRuaro** [comment]
I'm having this pop up after I typed in my twitter account credentials (it happens on both my personal twitter account, and my other twitter account which has access to the twitter api)![Screenshot_20210629_174223.jpg](https://user-images.githubusercontent.com/69240261/123776176-a0266e80-d901-11eb-8ea9-25e9be175e43.jpg)

**Comment by robertodoering** [comment]
Hm that's strange. Can you confirm that you put the correct callback url `harpy://` in your api settings?
What happens when you restart the app? Are you still directed to the welcome screen?

**Comment by eRuaro** [comment]
Sure, here's my API settings. ![Uploading harpy.png…]() Same thing happens when I restart the app. Looking at the terminal it has this error on it.

```E/FA      ( 2567): Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI```

The link redirects to firebase, I'm assuming I have to configure firebase as well?

**Comment by robertodoering** [comment]
Can you pull master and try again?

**Comment by eRuaro** [comment]
Got it to work now! The login error still persists on the pro version though.

**Comment by eRuaro** [comment]
If I understand the issue correctly, I should wrap the search screen in a scaffold widget right? And from there, add a list tile to the drawer that navigates to the search screen?

**Comment by robertodoering** [comment]
Great! It's fine if it just works for the free version for now.

Right now the `SearchScreen` is used in the `HomeTabView` and just builds the content with the search buttons and trends list.
Additionally we also want a list tile in the home drawer that will navigate to a separate search screen.

I would first rename the `SearchScreen` to something like `SearchScreenContent`.
Then add a new `SearchScreen`. The new `SearchScreen` only needs to build the `SearchScreenContent` with an app bar.
One option would be to just wrap it in a scaffold with a static app bar but that wouldn't be so nice.
Instead we can use a `HarpySliverAppBar` in the `SearchScreenContent`'s `CustomScrollView`.

Therefore I would add a parameter to the `SearchScreenContent` which will be set in the `SearchScreenContent` to provide the `HarpySliverAppBar`.
For navigation you can add a route string to the new `SearchScreen` and navigate it via a named route analog to other screens.

If you have any specific questions let me know

**Comment by eRuaro** [comment]
Hey, Robert! Sorry been busy with school work. Where do I add the `HarpySliverAppBar` in the `SearchScreenContent`?  Do I make it as the first widget in the `CustomScrollView` `slivers`? 

```
child: CustomScrollView(
        slivers: <Widget>[
          const HarpySliverAppBar(
            //Add content
          ),
          SliverPadding(
            padding: DefaultEdgeInsets.all().copyWith(bottom: 0),
            sliver: SliverList(
              delegate: SliverChildListDelegate(
                <Widget>[
                  _buildUserSearchCard(),
                  defaultVerticalSpacer,
                  _buildTweetSearchCard(),
                ],
              ),
            ),
          ),
..........
```

**Comment by robertodoering** [comment]
Hey @eRuaro,
yes exactly. It just has to bee the first sliver in the list, just like you showed.

**Comment by eRuaro** [comment]
I ran into an error while building the app.
```
Launching lib\main.dart on vivo 1723 in debug mode...
lib\main.dart:1
+++
No keystore defined. The app will not be signed.
Create a android/key.properties file with the following properties:
storePassword
keyPassword
keyAlias
storeFile
+++
Parameter format not correct -
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
error: warnings found and -Werror specified

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':connectivity:compileDebugJavaWithJavac'.
```

I'm building the app on my android device with whose version is Android 9 (API 28).

**Comment by eRuaro** [comment]
I've tried the answers listed here: https://stackoverflow.com/questions/64791058/warning-options-source-value-7-is-obsolete-and-will-be-removed-in-a-future-re. But the same errors still appear.

**Comment by robertodoering** [comment]
Well, sounds like you are using and old java version. If you haven't already try installing java 8 and change your `JAVA_HOME` to it.
You managed to build the app before, right? What did you change to run into the issue now?

**Comment by eRuaro** [comment]
Yep, I've tried it on Java 8 and Java 15. It seems to be a recurring issue with the `connectivity` plugin.
