### ISSUE TITLE
Suggestion: Adjustment to the Tweet's Image Box Sizing

### ISSUE THREAD

**Issue by 8227846265** [robertodoering/harpy#360]
I just noticed that the image size is cropped on Harpy. Perhaps the image box size can be adjusted to accommodate rectangle images.

Twitter Account For Example:
https://twitter.com/mullvadnet

Screenshot / Image Comparison
Mullvad on Harpy
![image](https://user-images.githubusercontent.com/66582769/118218405-e9357700-b4a9-11eb-8f60-784855c071e9.png)

Mullvad on Twidere
![image](https://user-images.githubusercontent.com/66582769/118218422-f2bedf00-b4a9-11eb-9d68-b0618490747e.png)

**Comment by robertodoering** [comment]
Thanks for the suggestions @8227846265!

This is a duplicate of #347.
I am working on that feature right now and will add it to the next release which will come out this weekend :)
