### ISSUE TITLE
Add Tweet Bookmarks 

### ISSUE THREAD

**Issue by KememChan** [robertodoering/harpy#361]
add Twitter Bookmarks support, or if its limited by twitter then add own harpy tweet bookmarks!

**Comment by robertodoering** [comment]
Thanks for the suggestion @DayatXD!

Twitter doesn't provide any API for the Bookmarks yet, but with Twitter working on their new API v2.0 it is quite possible that support will come in the future.

For that reason I want to wait for the new API before implementing my own solution for bookmarking tweets :)

I will keep this issue open and mark it as blocked for now.

**Comment by DayatXD** [comment]
if you implemented own harpy bookmarks that can delete individual bookmarks that would be cool, because twitter only have allow to delete all bookmarks only.

**Comment by ITSM3LMT** [comment]
Maybe try integration with getdewey.co that way we can just import bookmarks to dewey then see in app.I know this is just a temporary solution but it is a solution that will keep us happy until one day when Twitter drops it bookmarks api.
