### ISSUE TITLE
Twitter + Firefox ≠ Harpy

### ISSUE THREAD

**Issue by 8227846265** [robertodoering/harpy#366]
When opening Twitter links on Firefox.

It doesn't seem to open it on Harpy immediately despite the "Open links in app" is enabled.

The option "Open in app" doesn't also appear in the menu of Firefox as well.

**Comment by robertodoering** [comment]
Thanks for the suggestion!

Support for handling twitter urls is already planned:
https://github.com/robertodoering/harpy/issues/256
