### ISSUE TITLE
Add muting hashtags

### ISSUE THREAD

**Issue by robertodoering** [robertodoering/harpy#367]
Hashtags should be able to be 'muted'.
- Muted hashtags are filtered from the timeline
- Hashtags can be muted either permanently or for a specific duration
- A long press on a hashtag should open a bottom sheet with actions to mute a hashtag
- Muted hashtags differ from filtered hashtags (through a timeline filter) that they are muted globally and (optionally) only for a given time

**Comment by nplettenberg** [comment]
Does the Twitter API provide this function or do we have to handle it on the client side?
My first quick search in the API documentation did not give me any results.

**Comment by robertodoering** [comment]
We will implement it locally (the same way we implemented the timeline filters) since the api doesn't provide that functionality.

The `handleTweets` function in `handle_tweets.dart` is used to transform every tweet list response and can be expanded to check for tweets with muted hashtags and remove them.
