### ISSUE TITLE
Video Player Control Enchantment 

### ISSUE THREAD

**Issue by DayatXD** [robertodoering/harpy#369]
Video progress bar should be auto hide within 5 second, to show it back just one tap the video

To open the video (like black background) its with double tap the video instead of one tap

To pause video double tap in middle, instead of one tap when open video mode or fullscreen. this control can't function in background video mode because double tap is to open video (like black background)

**Comment by robertodoering** [comment]
There are a couple problems I see with this:
- The gestures you suggested conflict with the existing double tap to fast forward / rewind
- Using a double tap on the video to toggle fullscreen and having a double tap in the middle to pause the video can easily lead to accidentally toggling fullscreen when you meant to pause and the other way around
- Having the overlay hide will make the video player feel less responsive when you have to tap twice to pause and make it overall more clunky. I image there are lots of situation where you want to scroll through your timeline, check out the first 10s of a video and then continue scrolling. Having to spend that extra time to toggle the playback feels bad

If you want to have the overlay hidden you can view the video in fullscreen.

**Comment by DayatXD** [comment]
I suggest this so the overlay gone, i dont want fullscreen to just make the overlay gone, i want watch video without fullscreen too...
