### ISSUE TITLE
Remove 'Compose tweet' button from the home drawer

### ISSUE THREAD

**Issue by vrindavan** [robertodoering/harpy#377]
We can already directly compose tweets, so I think you can remove the compose button from the side menu.

The translate feature is good, to make it more cleaner you can either put it in the 3 dots context menu for tweets or make it optional for user to use it directly on tweets or not.

Also, the reply feature is in the 3 dots, you can put it in place of the translation button for faster access. It is more widely used than translate.

![Screenshot_20210531-162429_Harpy Free](https://user-images.githubusercontent.com/50140643/120183036-cbe40500-c22c-11eb-98e1-a0f52f4b5723.png)
![Screenshot_20210531-162450_Harpy Free](https://user-images.githubusercontent.com/50140643/120183047-cdadc880-c22c-11eb-919a-b0f7d74d0346.png)

**Comment by robertodoering** [comment]
I think removing the 'compose tweet' button from the drawer is fine.

However I want the translate button to stay visible in the tweet card by default and keep the reply button in the context menu.
Also, you will be able to arrange the order of the buttons and their locations in the future with #304. With that you can can customize the actions the way you want them.

I'll change the title accordingly and add this issue to the board :) Thanks.

**Comment by vrindavan** [comment]
Awesome 😇
