### ISSUE TITLE
Pause Previous Video When New Video is Played

### ISSUE THREAD

**Issue by 8227846265** [robertodoering/harpy#379]
I notice that whenever there are two tweets are both are videos.

Wherein the first tweet is played, you scroll down a bit, and you play the second video tweet.

Both will be played together.

My suggestion is to automatically pause the previous video when playing a new video.

**Comment by xiprox** [comment]
Somewhat related: may also want to pause videos that go offscreen.

Quite often I start a video and scroll a bit, then have to scroll back when I'm reminded offscreen videos don't get paused.

**Comment by robertodoering** [comment]
Thanks for the request!

This is definitely very useful and almost expected, I am surprised there isn't an issue for that already.
I will add it to the board :)

@xiprox Having videos pause as soon as they are scrolled out of view is also a great idea! There is an issue for that already: #345.
