### ISSUE TITLE
Support for Fleets

### ISSUE THREAD

**Issue by Quinten0508** [robertodoering/harpy#381]
Adding support for posting and viewing Fleets would be great!

Optionally a toggle in the settings to disable Fleets would be a good addition too, as there's some people who prefer to not have Fleets as they don't use them and it takes up part of their screen.

**Comment by scottiefalkon** [comment]
I hardly ever see anyone really use fleets. Even major news and sports
accounts. I honestly expect Twitter to kill them off. Don't know how much
effort adding them would take. But, would probably not be worth it. My
opinion of course.

**Comment by robertodoering** [comment]
I would love for harpy to eventually be a complete twitter client and support fleets as well.
However Twitter doesn't provide the functionality for 3rd party Twitter clients to add fleets yet.
They are working on a new version of their API which might allow us to support Fleets eventually, but only time will tell.

For now I will add it to the list as blocked, thanks for the suggestion!

**Comment by robertodoering** [comment]
Looks like @scottiefalkon was right and twitter is removing fleets 😄 
https://blog.twitter.com/en_us/topics/product/2021/goodbye-fleets

So since this will be obsolete, I will close this issue ⚓
