### ISSUE TITLE
Allow To Copy Twitter Username in Twitter User Profile Page

### ISSUE THREAD

**Issue by 8227846265** [robertodoering/harpy#384]
Please allow users to able to copy the Twitter username if hold tap on a Twitter User Profile page.

![Screenshot_20210624-092201_Harpy_Free](https://user-images.githubusercontent.com/66582769/123187934-bb424a00-d4cd-11eb-8a9d-b4e87a03f6ff.png)

**Comment by robertodoering** [comment]
This makes a lot of sense, thanks for the suggestion!
It's a really small thing, I will add it to the board and I will make sure it's in the next release :)
