### ISSUE TITLE
[Feature Request] Additional Filters on Twitter User Profile Page

### ISSUE THREAD

**Issue by 8227846265** [robertodoering/harpy#385]
Please add additional filter option to find Exact Keywords / Phrase / Hashtag tweeted by User when you use the Filter function available on top right when viewing a Twitter User Profile page. 

Currently it only has filter by Type of Tweet and Excludes.

Since we already have Exclude, perhaps we can add additional Include filter function.

![Screenshot_20210624-091249_Harpy_Free-01](https://user-images.githubusercontent.com/66582769/123187434-be890600-d4cc-11eb-8834-bf25602d1977.jpeg)

**Comment by robertodoering** [comment]
Thanks again for the suggestions!
I can see that this will be useful for some people.

I plan to redesign the timeline filter (#341) and added your request to add a 'includes' filter in the issue.

Since this is now part of #341 I will close this issue.
