### ISSUE TITLE
unable to download media

### ISSUE THREAD

**Issue by stanzinnamgyal** [robertodoering/harpy#392]
Hi Roberto,

whenever I try to download an image/video, the app says downloaded, but I don't get any notification nor am I able to locate any downloaded file.

please help. 

I'm Running Android 10

**Comment by robertodoering** [comment]
Hey @stanzinnamgyal
Images / videos are downloaded into the Downloads folder. Can you verify that they aren't saved at all?
If they aren't shown in your photo viewer please check if you can find them with a file explorer.

**Comment by L31FY** [comment]
I was having the same issue and had to clear my app data and repermit storage before they would save. Indeed nothing would save at all before I did that. Now they're not shown in any gallery apps and I have to manually dig through files to find things in the download folder still.

**Comment by robertodoering** [comment]
@desick 
What Android version are you running and what phone model are you using?

**Comment by robertodoering** [comment]
Fixed with 0.9.0
