### ISSUE TITLE
Cannot like anything (limit reached) 

### ISSUE THREAD

**Issue by PascalDk** [robertodoering/harpy#396]
I have this message (bottom) coming anytime I want to Fav a tweet

Have absolutely no idea why... 

![Screenshot_20210729-090318.jpg](https://user-images.githubusercontent.com/5103378/127447147-facfd26d-b73d-4a94-b588-44f199d8735d.jpg)

**Comment by robertodoering** [comment]
Hey @PascalDk 
Thanks for reporting the issue.
This is fixed on master. The fix will be released with the next update :)
