### ISSUE TITLE
Phoenix theme missing

### ISSUE THREAD

**Issue by Steve-Mr** [robertodoering/harpy#398]
In this [commit](https://github.com/robertodoering/harpy/commit/34946d476a45c50d5323ff4cd336325c7b3df666) the phoenix theme was removed, will it be re-add to harpy soon?

**Comment by robertodoering** [comment]
I removed the phoenix theme because I wasn't happy with it.
I don't have plans to bring it back. However, once the pro version will be released (hopefully soon), then you can create your own custom themes and one that is the same or similar to the old phoenix theme :)
