### ISSUE TITLE
Fix user profile banner not always covering available space 

### ISSUE THREAD

**Issue by Goooler** [robertodoering/harpy#428]
- The status bar hight is wrong and image is not complete.
- Nickname font baseline is too low to over the bottom of background.

![Screenshot_20210910-145647.jpg](https://user-images.githubusercontent.com/10363352/132813912-a98294b0-e0aa-4fc4-9350-803be2fab632.jpg)

**Comment by robertodoering** [comment]
Looks like the image isn't fully covering the header on your device, which is determined by the available height.
This should easily be fixable by setting fit of the background image to `BoxFit.cover` instead of `BoxFit.contain` in `user_banner.dart`.

Thanks for reporting the issue @Goooler :)

**Comment by Goooler** [comment]
And I suggest don't show big nickname when profile banner is expanded, it's duplicated with nickname in prifile card and not graceful.

**Comment by robertodoering** [comment]
This has been fixed and will be released with the next update :)
