### ISSUE TITLE
Long press to open preview

### ISSUE THREAD

**Issue by solargent** [robertodoering/harpy#433]
I would love the ability to long press on a piece of media - image, GIF, video - and have that be my preview action, in additional to just touching them. I find this UX (long press to preview, release press to close preview) smoother than touching to preview and swiping to close.

**Comment by robertodoering** [comment]
Thanks for the suggestion!
I personally don't like having the delay that comes with a long press but I can see where you are coming from.

In the future, I can imagine allowing the user to set custom actions on media / entities based on the gesture.
E.g:
- Map gestures like 'tap', 'long press', 'double tap' to actions depending on the type:
  - For media: 'preview', 'copy url', 'share', etc.
  - For @mentions: 'preview user', 'show user (open user profile screen)', 'copy user @handle', 'copy user name', 'copy url', 'share', etc.
  - etc.
This would allow you to then allow you to preview media on a long press.

I will create that issue in the future and then link it here and close this one. Until then I will keep it open and add it to the project as a reminder :)

**Comment by the-argent** [comment]
This sounds like a much more useful feature! It would also allow people to mimic Instagram's double-tap-to-like, which is well liked by some people.
