### ISSUE TITLE
(Consider) Include the authenticated user's retweets in the home timeline

### ISSUE THREAD

**Issue by Blackhawke** [robertodoering/harpy#440]
First, let me thank you for a great app. If you decide to to a pre-sale for your beta testers, let me know!

The issue: Yesterday I discovered my RTs are not showing up in timelines. QTs are. Replies are. Tweets are. But straight old RTs are *not*. My wife uses the official twitter app or site and went looking for an RT I referenced. It was in my profile, but it wasn't in the twitter timeline. So I checked your app and Owly (which I still have around) both. It wasn't in any of those timelines, but as with official Twitter, it *was* on my profile page.

Not sure what's up with that, but I thought you should know.

Details (I'm doing this in the mobile app, so if you have a bug report form, I don't see it): Samsung Note 9 running the latest official OS.

**Comment by robertodoering** [comment]
Thanks for the issue @Blackhawke!

3rd party Twitter apps like Harpy use the [Twitter api](https://developer.twitter.com/en/docs/twitter-api) to request the user data from Twitter.
The home timeline, which includes your own tweets and the tweets of users that you follow, does not include your own retweets. For whatever reason Twitter has decided that your own retweets should not be part of the home timeline.

Your own retweets do show up in your own profile, though.

As a work around we could request the user profile tweets and merge the retweets with the home timeline. This is something to consider in the future but is not something I plan to implement right now. I will move this ticket in the backlog for now.

If you have any more questions or feedback feel free to comment them here or add new issues :)

**Comment by Blackhawke** [comment]
Thanks for getting back to me. The thing I forgot to mention is: My RTs still show up in the timeline when I use Owly. So this is a phenomenon unique to Harpy, not Twitter.
