### ISSUE TITLE
[Request]: Please consider 5 x 1 Widget

### ISSUE THREAD

**Issue by Nehemoth** [robertodoering/harpy#442]
I really love using twitter clients with a widget which in a single horizontal line allow me to jump to new tweets with a counter (TL), mentions, DM, New Tweet, settings.

I'm really loving this client already.

**Comment by robertodoering** [comment]
Thanks for the suggestion @Nehemoth.
I haven't planned adding widgets for harpy yet, but will keep this in mind for the future.
For now I will add this issue in the backlog :)

**Comment by Nehemoth** [comment]
Thank you. Really Appreciate it

**Comment by mda4mda** [comment]
I love the harpy client.  The lack of a widget is the only thing I think it would take to be the best Twitter client on Android.

**Comment by MaluNoPeleke** [comment]
I also would like to have a scrollable timeline widget and would even pay for it.
