### ISSUE TITLE
Disable retweets and likes in list

### ISSUE THREAD

**Issue by FunnyMonkeyBaz** [robertodoering/harpy#446]
Add a filter which lets us disable retweets and likes in a list

**Comment by robertodoering** [comment]
Thanks for the suggestion!
I don't see a big reason why someone would want to filter liked / retweeted tweets but I will consider adding it when working on #341. Do you have a specific use case for this filter?
Will close this ticket for now.

**Comment by robertodoering** [comment]
This will be possible with #352
