### ISSUE TITLE
Add system / push notifications

### ISSUE THREAD

**Issue by dnestico** [robertodoering/harpy#455]
Sorry I didn't know if this has been answered before but is it possible to add push notifications? If not no worries I'll just keep twitter app installed for that.

**Comment by pwd-github** [comment]
> Sorry but just to add to this if you do work on push notifications I was talking about "like, retweet, reply/qt, and new follower notifications".
> 
> Just like the Twitter app, it would be ideal if these were considered "quiet notifications" on Android.
> 
> Basically, when you get one of these notifications it doesn't actually vibrate your phone it just sends it quietly, unlike if you have tweet notifications on for an account that is not a quiet notification. Thanks!

Like was removed by Twitter, you can only get responses and retweets

**Comment by dnestico** [comment]
@pwd-github Ah that's a shame but honestly wasn't a priority for me anyways. I mainly care for replies and account notifications.

Also when he adds #130, I'd assume there are notifications for messages right? If not that kinda defeats the whole thing whenever that happens.

**Comment by pwd-github** [comment]
> @pwd-github Ah that's a shame but honestly wasn't a priority for me anyways. I mainly care for replies and account notifications.
> 
> Also when he adds #130, I'd assume there are notifications for messages right? If not that kinda defeats the whole thing whenever that happens.

Indeed, you get notifications for direct messages.

**Comment by dnestico** [comment]
Well that's good, would be pretty ridiculous if you didn't haha.

> Indeed, you get notifications for direct messages.
