### ISSUE TITLE
Move 'show members' from list app bar actions to the timeline top row

### ISSUE THREAD

**Issue by robertodoering** [robertodoering/harpy#462]
Currently the list timeline top row only includes a single button to refresh it.

The 3-dot-menu on the app bar includes a single entry 'show members'.

The 3-dot-menu can be removed and a button 'members' can be added to the right side of the top row.

**Comment by pedr0luiz** [comment]
Hi @robertodoering, can you explain this a litte bit more? I couldn't find the menu with the 'show members' entry.

**Comment by robertodoering** [comment]
When you are viewing the timeline of a Twitter List, there is a 3-dot-menu on the top right with a 'show members' action:
<img width=300 src="https://user-images.githubusercontent.com/20045287/141323586-e58a8414-c3eb-4546-9373-bb10baede9c1.png"/>

Instead we want this action moved to the top row of the timeline, where the refresh button is. I hope that explains it better

**Comment by pedr0luiz** [comment]
Ohhh i got it! I wasn't subscribed in any list so i couldn't access this page. I'm working on it right now.
