### ISSUE TITLE
Only load high quality image on image tap

### ISSUE THREAD

**Issue by dnestico** [robertodoering/harpy#463]
So I have high quality images on right now but am considering lowering it because it doesn't matter if I'm on data or WiFi, images take a long time to load sometimes and I think it might be because of that.

So maybe if possible add an option to ONLY load the image in high quality if it is tapped/enhanced, but while just normally scrolling in timeline do NOT load in high quality. Thanks!

**Comment by robertodoering** [comment]
Hey David,
I plan to add an option to load the best available image quality when previewing the image, just like you suggested. This is tracked with #365.

With this you can
- never load best image quality (default)
- only when previewing
- always load best image quality


I might also consider a toggle in the preview to load the best quality image when you have the first option enabled

**Comment by dnestico** [comment]
Nice!

**Comment by dnestico** [comment]
Hey just an update, maybe it was my old phone because I got the Google Pixel 6 Pro now and images seem to load much quicker! PS, The timeline scrolling in 120hz is buttery smooth I love it 👍🔥

**Comment by robertodoering** [comment]
That's awesome to hear! 🚀
