### ISSUE TITLE
Read Quote tweets option

### ISSUE THREAD

**Issue by dnestico** [robertodoering/harpy#469]
Please add a "quote tweets" button beside the retweet button that allows the user to read the quote tweets from a specific tweet.

Can probably be a shortcut to the search menu that just links the tweet maybe like the regular twitter app does to load the quote tweet replies. Thanks!

**Comment by robertodoering** [comment]
Am I understanding it correct, that you want to see every tweet that quoted your specified tweet?

With the Twitter API we can retrieve the retweets and likes for a tweet, but as far as I can tell we can't retrieve only quoted tweets (they might be returned together with the reetweets).
So this doesn't seem to be possible unfortunately

**Comment by dnestico** [comment]
Well I meant when you click on any tweet on the timeline to be able to read the quoted replies too. Sucks twitter API doesn't allow that rn.

**Comment by robertodoering** [comment]
Ah I get it now. It seems that you can't filter for quoted tweets at all in the twitter search, only for retweets unfortunately.

Maybe this will change with the Twitter API v2 in the future :p

**Comment by dnestico** [comment]
👀  https://twitter.com/TwitterDev/status/1504583305114447884
