### ISSUE TITLE
Tweet options/shortcuts

### ISSUE THREAD

**Issue by dnestico** [robertodoering/harpy#470]
Definitely not a must/deal breaker but a "nice to have feature" would be showing options/shortcuts on tweets like:

- download media button/button
- copy link shortcut
- the persons follower count
- show icon if users is following you on profile pic

![Screen Shot 2021-11-08 at 9 14 44 PM](https://user-images.githubusercontent.com/3034555/140849632-c76ced4b-24ed-4a9d-95b7-ed3728729478.png)
![Screen Shot 2021-11-08 at 9 15 55 PM](https://user-images.githubusercontent.com/3034555/140849634-bf84bc57-b2c1-40e5-82ad-47722339c90c.png)
![Screen Shot 2021-11-08 at 9 17 39 PM](https://user-images.githubusercontent.com/3034555/140849635-cbfff224-0daa-404b-af97-782a5301d991.png)

**Comment by robertodoering** [comment]
Thanks for the suggestions as always :)

Customization for the tweet card is planned with #304.
I have expanded on it to include some of your suggestions :)

If you have more ideas on what the tweet card content should (optionally) contain, feel free to add a comment in #304!
