### ISSUE TITLE
No action in close filter button, when nothing is selected

### ISSUE THREAD

**Issue by pedr0luiz** [robertodoering/harpy#472]
When there's no filters selected the behaviour of this button should be like this?

https://user-images.githubusercontent.com/38326603/141154296-a73443ce-10a9-40ca-8b50-9be29cc2164a.mov

**Comment by robertodoering** [comment]
Can you explain what behavior you are reffering to?

**Comment by pedr0luiz** [comment]
The button isn't closing the filter when nothing's selected.

**Comment by pedr0luiz** [comment]
I think it's related to [this line](https://github.com/robertodoering/harpy/blob/ab42202b56fee1da11c9d55763bcdbdbcadaeb70/lib/components/widgets/filter/filter_drawer.dart#L40)

**Comment by robertodoering** [comment]
Ah I see what you mean!
Yeah, this is intended because this button resets the filter and is not just closing the filter.

This might be a bit confusing, but the filter will be reworked soon anyway so we shouldn't put any affort in changing this for now :)

**Comment by pedr0luiz** [comment]
Ok, I got it!
