### ISSUE TITLE
Tweet button hidden when scrolling

### ISSUE THREAD

**Issue by dnestico** [robertodoering/harpy#475]
![Screenshot_20211112-220930~2.png](https://user-images.githubusercontent.com/3034555/141603785-5485824c-ead5-438b-9326-a014f5076d4b.png)

A floating tweet button would be helpful because unless it's a big but you have to scroll right to the top whenever you wanna compose a tweet everytime

**Comment by robertodoering** [comment]
You can also just swipe to the left and use the 'compose' button in the drawer, which I added as a compromise because I really don't want a floating action button present on screen at all times

**Comment by dnestico** [comment]
Alright thanks, that seems fine, was just confused about having to scroll all the way to the top to be able to tweet

**Comment by dnestico** [comment]
Hey coming back to this because I just saw what Twitter may be working on haha, how about something similar to this? If no then that's understandable. https://twitter.com/alex193a/status/1464246841139150853

**Comment by robertodoering** [comment]
@dnestico I will consider it, but I really like the clean look that you have without a dedicated compose button or text field
