### ISSUE TITLE
Can't tweet images

### ISSUE THREAD

**Issue by dnestico** [robertodoering/harpy#476]
Images seem to be broken, I just get this error, and if the tweet has text, the tweet will still send but without the image![Screenshot_20211112-221638.png](https://user-images.githubusercontent.com/3034555/141603844-0fcdd941-4559-4c15-9df1-89c40fafef1a.png)

**Comment by robertodoering** [comment]
Thanks for reporting the issue!
I can reproduce it on the live version but it got 'accidentally' fixed in the dev branch (#459) after it got refactored :)
