### ISSUE TITLE
Copying text doesn't parse html entities

### ISSUE THREAD

**Issue by robertodoering** [robertodoering/harpy#482]
When using the 'copy text' action on a Tweet.

E.g. `&lt;` won't be parsed into a `<`.

Should use the `parseHtmlEntities` function for the copied text

**Comment by pedr0luiz** [comment]
Hey @robertodoering, I'm trying to work on this, but the master branch have a lot of errors. Is that supposed to be like this or I'm missing some steps?

**Comment by pedr0luiz** [comment]
`lib/components/common/authentication/cubit/authentication_cubit.dart:14:6: Error: Error when reading 'lib/components/common/authentication/cubit/authentication_cubit.freezed.dart': No such file or directory
part 'authentication_cubit.freezed.dart';
     ^
lib/components/common/find_trends_locations/bloc/find_trends_locations_bloc.dart:12:6: Error: Error when reading 'lib/components/common/find_trends_locations/bloc/find_trends_locations_bloc.freezed.dart': No such file or directory
part 'find_trends_locations_bloc.freezed.dart';
     ^
lib/components/common/pagination/paginated_state.dart:3:6: Error: Error when reading 'lib/components/common/pagination/paginated_state.freezed.dart': No such file or directory
part 'paginated_state.freezed.dart';
     ^
lib/components/common/replies/cubit/replies_cubit.dart:10:6: Error: Error when reading 'lib/components/common/replies/cubit/replies_cubit.freezed.dart': No such file or directory
part 'replies_cubit.freezed.dart';
     ^
lib/components/common/timeline/cubit/timeline_cubit.dart:11:6: Error: Error when reading 'lib/components/common/timeline/cubit/timeline_cubit.freezed.dart': No such file or directory
part 'timeline_cubit.freezed.dart';
     ^
lib/components/common/timeline/filter/model/timeline_filter.dart:6:6: Error: Error when reading 'lib/components/common/timeline/filter/model/timeline_filter.g.dart': No such file or directory
part 'timeline_filter.g.dart';
     ^
lib/components/common/trends/cubit/trends_cubit.dart:12:6: Error: Error when reading 'lib/components/common/trends/cubit/trends_cubit.freezed.dart': No such file or directory
part 'trends_cubit.freezed.dart';
     ^
lib/components/common/trends_locations/cubit/trends_locations_cubit.dart:11:6: Error: Error when reading 'lib/components/common/trends_locations/cubit/trends_locations_cubit.freezed.dart': No such file or directory
part 'trends_locations_cubit.freezed.dart';
     ^
lib/components/common/trends_locations/data/trends_location_data.dart:7:6: Error: Error when reading 'lib/components/common/trends_locations/data/trends_location_data.g.dart': No such file or directory
part 'trends_location_data.g.dart';
     ^
lib/components/common/tweet/bloc/tweet_bloc.dart:17:6: Error: Error when reading 'lib/components/common/tweet/bloc/tweet_bloc.freezed.dart': No such file or directory
part 'tweet_bloc.freezed.dart';
     ^
lib/components/common/user_relationship/bloc/user_relationship_bloc.dart:9:6: Error: Error when reading 'lib/components/common/user_relationship/bloc/user_relationship_bloc.freezed.dart': No such file or directory
part 'user_relationship_bloc.freezed.dart';
     ^
lib/components/screens/compose/bloc/compose/compose_bloc.dart:10:6: Error: Error when reading 'lib/components/screens/compose/bloc/compose/compose_bloc.freezed.dart': No such file or directory
part 'compose_bloc.freezed.dart';
     ^
lib/components/screens/compose/bloc/post_tweet/post_tweet_cubit.dart:13:6: Error: Error when reading 'lib/components/screens/compose/bloc/post_tweet/post_tweet_cubit.freezed.dart': No such file or directory
part 'post_tweet_cubit.freezed.dart';
     ^
lib/components/screens/home/home_tab_customization/model/home_tab_configuration.dart:5:6: Error: Error when reading 'lib/components/screens/home/home_tab_customization/model/home_tab_configuration.g.dart': No such file or directory
part 'home_tab_configuration.g.dart';
     ^
lib/components/screens/home/home_tab_customization/model/home_tab_entry.dart:5:6: Error: Error when reading 'lib/components/screens/home/home_tab_customization/model/home_tab_entry.g.dart': No such file or directory
part 'home_tab_entry.g.dart';
     ^
lib/components/screens/lists/show/bloc/lists_show_bloc.dart:11:6: Error: Error when reading 'lib/components/screens/lists/show/bloc/lists_show_bloc.freezed.dart': No such file or directory
part 'lists_show_bloc.freezed.dart';
     ^
lib/components/screens/search/tweet/cubit/tweet_search_cubit.dart:11:6: Error: Error when reading 'lib/components/screens/search/tweet/cubit/tweet_search_cubit.freezed.dart': No such file or directory
part 'tweet_search_cubit.freezed.dart';
     ^
lib/components/screens/search/user/cubit/user_search_cubit.dart:9:6: Error: Error when reading 'lib/components/screens/search/user/cubit/user_search_cubit.freezed.dart': No such file or directory
part 'user_search_cubit.freezed.dart';
     ^
lib/components/screens/user_profile/cubit/user_profile_cubit.dart:10:6: Error: Error when reading 'lib/components/screens/user_profile/cubit/user_profile_cubit.freezed.dart': No such file or directory
part 'user_profile_cubit.freezed.dart';
     ^
lib/components/settings/theme_selection/bloc/theme_bloc.dart:15:6: Error: Error when reading 'lib/components/settings/theme_selection/bloc/theme_bloc.freezed.dart': No such file or directory
part 'theme_bloc.freezed.dart';`

**Comment by pedr0luiz** [comment]
I think I fixed it, but I can't test

**Comment by robertodoering** [comment]
Make sure to run the build runner when pulling master to trigger code generation
`flutter packages pub run build_runner build`
