### ISSUE TITLE
Add likes/retweets to mentions feed at top

### ISSUE THREAD

**Issue by dnestico** [robertodoering/harpy#488]
Adding this would make me feel comfortable with deleting the twitter app since its the only way to check this stuff right now. I understand if it's not a top priority of course! 

No idea if these links help but I tried haha!

https://developer.twitter.com/en/docs/twitter-api/tweets/likes/api-reference/get-tweets-id-liking_users

https://developer.twitter.com/en/docs/twitter-api/tweets/retweets/api-reference/get-tweets-id-retweeted_by 

![Screenshot_20211125-005354~2.png](https://user-images.githubusercontent.com/3034555/143388200-08050bf1-a376-4b19-81d8-d82fbfc795e7.png)

2nd image is example from Fenix 2 for Twitter
 ![Screenshot_20211125-042029.png](https://user-images.githubusercontent.com/3034555/143414441-78fedf90-9981-49db-b07e-ccb30d01bdcd.png)

**Comment by robertodoering** [comment]
Thanks again for the suggestions :)
Yes, this will for sure come as one of the new features that are implemented after adding the new api!
I'm also eager to have these alerts in the app and I'm glad we can have them now with the new api :)

**Comment by dnestico** [comment]
Yesss perfect!!
