### ISSUE TITLE
Add option to hide app bar when scrolling down

### ISSUE THREAD

**Issue by sboulema** [robertodoering/harpy#489]
I would like to be able to hide the app bar when scrolling down, instead of when scrolling up.

I set Harpy to remember scroll position, so to catch up with all tweets I scroll down and do not have to see the app bar.

Congrats on the Pro release! Was using the free version but switched to pro immediately. Still one of the cleanest Twitter apps out there :D

**Comment by robertodoering** [comment]
Thanks for the suggestion and your support! :)
This sounds good, we can group all of the app bar options together in the same step and make it a bit cleaner, thanks :)
