### ISSUE TITLE
Mute replies/rts on individual timelines

### ISSUE THREAD

**Issue by dnestico** [robertodoering/harpy#490]
It would be nice if I can just mute rts/replies on individual timelines, for example I want to mute replies when I go look at my own profile and on my lists, but when I mute them, it also seems to apply to every single timeline including my home timeline.

Maybe I'm doing something wrong?

**Comment by robertodoering** [comment]
At the moment the home timeline and the user profile have separate filters.
Yes, it makes a lot of sense to be to set filters per user / list. I will add this as a requirement in #341.
Thanks :)
