### ISSUE TITLE
Inconsistent text (lowercase, uppercase...)

### ISSUE THREAD

**Issue by sheeepdev** [robertodoering/harpy#491]
Some parts of Harpy are inconsistent with the capitalization of the letters (e.g the name of the app in the play store is "harpy for Twitter" instead of "Harpy for Twitter" or "harpy for twitter") This is also happening in the app, the date is lowercase, but the name of the app used to tweet is normal.

**Comment by robertodoering** [comment]
The "brand" name "harpy" should be lowercase. It used to be uppercase but I recently transitioned away from it.
I just fixed the Twitter api application name (for harpy free), so it will use lower case now when tweeting, thanks for letting me know!

I believe the only adjustment still left to do is the animated logo, which I will have to update in the future. If you find more please let me know :)

**Comment by sheeepdev** [comment]
> The "brand" name "harpy" should be lowercase. It used to be uppercase but I recently transitioned away from it. I just fixed the Twitter api application name (for harpy free), so it will use lower case now when tweeting, thanks for letting me know!
> 
> I believe the only adjustment still left to do is the animated logo, which I will have to update in the future. If you find more please let me know :)

Sorry for commenting late, but the Twitter in harpy for twitter is still capitalized, so its "harpy for Twitter".

**Comment by robertodoering** [comment]
Yeah as it should be

**Comment by sheeepdev** [comment]
It is still inconsistent... It is wierd for the name to be "harpy for Twitter"
