### ISSUE TITLE
Fix: Autocap after a period or special characters.

### ISSUE THREAD

**Issue by Nehemoth** [robertodoering/harpy#496]
The first letter composing a tweet should be in Capital and also the same should happen after an special character.

Thanks

**Comment by dnestico** [comment]
I agree, also a little different but stuff like this would just make the tweet process a lot quicker

Twitter app: open tweet drawer, keyboard automatically opens, letters are capitalized based off phone settings, send tweet, tweet drawer closes automatically. **Done quickly.**

Harpy right now: open tweet drawer, tap to open keyboard, tap to capitalize text, send tweet, close tweet drawer manually. **Takes a little longer to tweet on harpy rn.**

**Comment by robertodoering** [comment]
I agree, I am surprised that flutter doesn't use the platform settings for capitalization but we can simply default to auto capitalizing the first word
