### ISSUE TITLE
Search suggestions

### ISSUE THREAD

**Issue by dnestico** [robertodoering/harpy#498]
Search suggestions as you type a hashtag (#) or  username (@) 

Both while typing a tweet or in the search tab would be nice

**Comment by robertodoering** [comment]
We had these suggestions before when composing a tweet but I had to remove them temporarily.
Will add them again, also great idea to have the suggestions in the search 👍

**Comment by monee121** [comment]
I would like the ability to search in followers/following from the profile. Like a search bar at the top so you can find someone you follow. Or auto populate followers/following first from the general search bar. Not sure which option works best from the dev side.  

If I only remember a portion of a name and search it, it doesn't come up first in results so I have to already know their full name which defeats the purpose of searching sometimes in my opinion.
