### ISSUE TITLE
View who has liked a tweet

### ISSUE THREAD

**Issue by Yusuf-Uluc** [robertodoering/harpy#499]
View who has retweetet or liked a tweet. Would be nice to have. Could be implemented by eg. long pressing the like button or retweet button.

**Comment by robertodoering** [comment]
Thanks for the suggestion!
I like the idea of a long press on the like & retweet button

**Comment by dre8597** [comment]
Hello 👋🏾 , I've started working on a feature that does exactly this and would love to open a PR for it! A couple of things, first I noticed that the current Twitter API client only allows us to view users that retweeted a tweet but, not a way to view the likes, and second I currently added the 'retweeters' option as a new addition in the `_showRetweetButtonMenu` section. Would you want to wait until the like option is available (API V2) or release it as a separate feature? 

https://user-images.githubusercontent.com/21962908/146093807-9f76e5d0-4abe-4073-84c7-742d37520e3c.mp4

**Comment by robertodoering** [comment]
@dre8597 
That looks awesome, great work!
Yeah you are right, we will have to wait for the api v2 implementation until we can show the likes but we can definitely release this separately!
Having it as a menu entry in the retweet menu seems great too. Feel free to open up a PR for it, I would really appreciate it :)

**Comment by dnestico** [comment]
I like this feature! But can it be changed so that if we press button to bring up the options it doesn't unretweet the tweet if already retweeted.

Like maybe if the tweet is already retweeted if we hold the button it can bring up the options to see but without unretweeting.

**Comment by robertodoering** [comment]
@dnestico holding down the retweet button will navigate to the retweeters list.
But thinking about it, it does make sense to bring up the menu instead of immediately unretweeting on press, since you also might want to quote a tweet after retweeting for example.

I will add this with the next update, good suggestion 👍

**Comment by dnestico** [comment]
Nice!
