### ISSUE TITLE
Add Android 12 'Material You' theme

### ISSUE THREAD

**Issue by dnestico** [robertodoering/harpy#504]
I've had android 12 on my Pixel 6 Pro for a while now and I am loving the new dynamic colour themes. I also love harpy's theme but I think it would be cool if the menu icons and text colour in the menus were integrated with dynamic colours for those who want to use it.

So dynamic colour theming in the menus is the idea which I think would be cool.

**Comment by robertodoering** [comment]
It's definitely a great idea to add support for Material You into harpy. I will check and see how well it is supported in Flutter and plan to implement it soon :)

I am thinking of adding it as an additional selectable theme if the user is using Android 12 for both free and pro. Mapping the color scheme to a harpy theme should be pretty straight forward.

**Comment by dnestico** [comment]
Nice! 👍

**Comment by robertodoering** [comment]
Flutter's material you support is very limited at the moment. I'll mark this issue as blocked until we can implement proper support in future updates

**Comment by dnestico** [comment]
Alright 👍

**Comment by rnagabhyrava** [comment]
Just an FYI, 


https://github.com/flutter/flutter/issues/91605
