### ISSUE TITLE
Add restore timeline position for all timelines 

### ISSUE THREAD

**Issue by robertodoering** [robertodoering/harpy#505]
The home timeline currently restores its position when the user restarts the app (configured in `settings > restore home timeline position`).

The behavior should exist for user and list timelines.

In addition, the option should be updated to allow for timeline-specific configuration

**Comment by AmjadAGA** [comment]
Still not working in the last Verizon, only restores 2 hours backwards.

**Comment by AmjadAGA** [comment]
Its not working, the maximum timeline restores position is 2 hours before. And most of the time it doesn't restore the right position but the previously unloaded tweet since the closure of the app.

**Comment by robertodoering** [comment]
@AmjadAGA this feature is `open`, meaning it hasn't been added to harpy yet

**Comment by 702573N** [comment]
Very import but missing feature.
