### ISSUE TITLE
120hz

### ISSUE THREAD

**Issue by Mica007** [robertodoering/harpy#512]
Please add support for 120hz devices.

**Comment by dnestico** [comment]
My Pixel 6 Pro has 120hz and even without it it still runs smoothly for me, but would be awesome though

**Comment by robertodoering** [comment]
What device do you have where the refresh rate is not set to 120hz? In the past Flutter had issues with OnePlus devices but others should work fine.

I had gotten by hands on a RedMi Note 10 Pro for testing recently and harpy was running at ~170 fps on a 120hz display.

**Comment by robertodoering** [comment]
@dnestico Is your pixel limiting the refresh rate while using harpy?

**Comment by dnestico** [comment]
![Screenshot_20211231-053817~2.png](https://user-images.githubusercontent.com/3034555/147818943-3cbdf148-2cff-4f99-9a13-09114d1e49f5.png)
While actually nevermind! Looks like it is actually 120Hz, that explains why it's such a smooth experience on the Pixel 6 Pro over my S10.

**Comment by Mica007** [comment]
I am using a Note 20 Ultra. It was at 60 hz earlier but now seems to be at 120hz. Sorry!
