### ISSUE TITLE
Sorting comments 

### ISSUE THREAD

**Issue by Quinten0508** [robertodoering/harpy#517]
Right now on tweets comments are sorted by newest comment first (I believe). I'm unsure how twitter itself sorts them, but sorting by new definitely isn't the way. It breaks threads and all I can see on tweets with hundreds of comments are just people @'ing others. Would it be possible to implement another way of sorting comments?

**Comment by robertodoering** [comment]
Viewing all comments for a tweet is actually not supported through the Twitter API. In harpy we use the tweet search endpoint to request tweets that are replying to the parent tweet (i.e. the comments of a tweet).
This workaround doesn't allow for a proper sorting, so we can't change this yet unfortunately.

That said, I wouldn't be surprised if Twitter adds a proper endpoint to view the comments of a tweet in their new API v2. When they do harpy will add include proper viewing and sorting for the tweet comments.
