### ISSUE TITLE
Add 'download all images' / 'download gif' / 'download video' tweet action

### ISSUE THREAD

**Issue by robertodoering** [robertodoering/harpy#519]
Currently downloading tweet media is possible through a long press on the preview in the tweet card or when opening the media overlay.

Having an action in tweet action bottom sheet (available through the 3-dot button) to download media allows the addition of a 'download all images' action.

- Requires changing the download service to support for multiple parallel downloads
- Requires updating the download dialog to support renaming multiple files
  (alternatively not allow renaming when multiple images exist)

**Comment by kitzai523** [comment]
hi,good features but the image download  cant find/show direct on the photo library,previous me use other app same issue ,they said the google app issue on it
