### ISSUE TITLE
Search option need some love.. Please add all the default Twitter things like suggestion, different trending section (like sport, entertainment etc)

### ISSUE THREAD

**Issue by Kalpataru6** [robertodoering/harpy#520]
Also after we search a hashtag there should be short by latest option like in default Twitter.. Don't make a completely different Twitter app.

**Comment by robertodoering** [comment]
> Don't make a completely different Twitter app

I will make whatever app I want to make.


Multiple search improvements are planned. You can find them by looking at existing issues
https://github.com/robertodoering/harpy/issues?q=is%3Aissue+is%3Aopen+search
