### ISSUE TITLE
Save recent searches

### ISSUE THREAD

**Issue by dnestico** [robertodoering/harpy#521]
One feature I love about the twitter app is it saves my searches including accounts and I can come back to it anytime and they'll be there waiting.

Would be a nice addition to harpy's search. 

![Screenshot_20220108-070505~2.png](https://user-images.githubusercontent.com/3034555/148643571-96579200-2d85-4067-820d-3e30972bda68.png)

**Comment by robertodoering** [comment]
Yeah this will definitely be a useful feature, a ticket for it already exists: #283 so I'll be closing this one
