### ISSUE TITLE
Fix applying invalid search filter

### ISSUE THREAD

**Issue by knotsid** [robertodoering/harpy#523]
<img width=300 src="https://user-images.githubusercontent.com/36338447/148890204-c2ac6c3c-f2f3-4eac-bae2-e6d96d853606.jpg"></img>

When filtered to exclude retweet, it bugs out.

**Comment by robertodoering** [comment]
Thanks for reporting the issue.
It seems like you only use the retweets (and possible other) filters in combination with other search filters (e.g. some keyword).
We can fix it by preventing the user to add an invalid search filter.

**Comment by knotsid** [comment]
> Thanks for reporting the issue. It seems like you only use the retweets (and possible other) filters in combination with other search filters (e.g. some keyword). We can fix it by preventing the user to add an invalid search filter.

No, I just used retweet filter.

**Comment by robertodoering** [comment]
What I mean is that the Twitter search requires more than just filtering retweets in the Tweet search (e.g. a search for "harpy" and filtering out retweets is fine)
