### ISSUE TITLE
Add compose tweet floating action button

### ISSUE THREAD

**Issue by FerasK0** [robertodoering/harpy#524]
While using harpy i noticed it's quite inconvenient to go all the way up or swipe right to tweet and the swipe left to go back to my timeline.

I think a floating button or something like that would be awesome.

**Comment by robertodoering** [comment]
Personally I don't like having a floating action button, but it has been requested many times now where I will consider making it optional.

We can add an option "Show floating compose button" in general settings which will show a static floating action button in the home screen and user screen.

**Comment by FerasK0** [comment]
Well, more choices makes your app more customizable and appealing imo.
I agree with you on making it an on-off option, that would suit the needs of everyone.

**Comment by scottiefalkon** [comment]
I like this idea. Unless there's another option someone can think of to be
able to quickly and easily compose. I'm not the biggest fan of floating
buttons either. But, there are too many steps to create a new tweet
right now.

**Comment by dnestico** [comment]
Yessss! Thanks @robertodoering !
