### ISSUE TITLE
Show exact follower count on following & follower button long press

### ISSUE THREAD

**Issue by dnestico** [robertodoering/harpy#526]
An option that shows the exact number rather then a rounded up number like it is now when over 1k followers.

**Comment by robertodoering** [comment]
I wouldn't want a dedicated setting for that but having the ability to see the exact number is a great idea :)

I think a tooltip when long pressing on the followers / following count would be nice with the exact number, what do you think of that?

**Comment by dnestico** [comment]
Yup that sounds good 👍
