### ISSUE TITLE
Fix RTL language text layout

### ISSUE THREAD

**Issue by FerasK0** [robertodoering/harpy#527]
I noticed while using harpy that Arabic text are LTR and if mixed with English characters the tweets just becomes unreadable and you can't know where the tweet starts or ends.

I suggest making the Arabic text always RTL Even if there's some English characters in between. 

Here's an example and I'll translate it as if you're reading in Arabic:
![20220116_232316](https://user-images.githubusercontent.com/83197825/149676725-a5b84671-f066-463a-8713-1309f66d4814.jpg)

"It's facing development difficulties - Rumor GTA5 New gen Edition of 
(URL)
And maybe it'll be delayed again"

And here's an example on how Telegram treats RTL Characters (which includes Arabic and better imo):

![20220116_232818](https://user-images.githubusercontent.com/83197825/149676888-476a3738-2a3c-4a7a-ace5-d2e78b7c4013.jpg)

"The New gen Edition of GTA5 is facing development difficulties - Rumor 
(URL)
And maybe it'll be delayed again"

I hope you understand what I mean :)

**Comment by robertodoering** [comment]
Thanks for the detailed description @FerasK0!
There actually is an issue for this already here: #314 but I will be closing that once since this shows the issue better.

The fix should be relatively simple - we get the language through Twitter so we can just adjust the text align based on it.
