### ISSUE TITLE
Improve media upload behavior

### ISSUE THREAD

**Issue by FerasK0** [robertodoering/harpy#531]
Hello again, apparently (at least to me) uploading a long vid causes a huge power consumption while no progress is made, in a span of 5 minutes the battery went from 12% to 2% while the vid is uploading, and didn't upload till I plugged my phone.
My hypothesis is there was some loop code or something that caused the problem but I'm no expert.

![image](https://user-images.githubusercontent.com/83197825/150118840-5ab9e66f-a900-4a5a-b057-1a7b33fa3b70.png)

other important info:
- My note9 was into medium power saving which limits CPU speed to 70%.
- I didn't encounter this kind of behavior in other apps while in the same "power saving mode". 
- The uploading circle was running and didn't freeze during uploading

I suggest that if it couldn't be optimized somehow, put a dialog that notifies the user to charge their device or whatever action the condition requires.

**Comment by robertodoering** [comment]
Thanks for reporting the issue @FerasK0

We have to encode the video before uploading it to Twitter, so the cpu intensive work is expected.

I agree though, that a dialog should warn the user beforehand. Also we should show a progress bar with the % progress and allow to cancel the upload.
So there are definitely some improvements that we can make here. I will add it to the project :)

**Comment by FerasK0** [comment]
> Thanks for reporting the issue @FerasK0
> 
> We have to encode the video before uploading it to Twitter, so the cpu intensive work is expected.
> 
> I agree though, that a dialog should warn the user beforehand. Also we should show a progress bar with the % progress and allow to cancel the upload.
> So there are definitely some improvements that we can make here. I will add it to the project :)
> 

Don't mention it ;)
Although I recreated the same situation with the power saving mode off and the same problem occurred, so yeah thats weird.

**Comment by dnestico** [comment]
I agree with the progress bar because it took 5 minutes to upload 30 second video over LTE. I understand there's probably nothing you could change make uploading faster sadly though.

**Comment by robertodoering** [comment]
I might can make some improvements and speed it up, I will experiment with it :)

**Comment by dnestico** [comment]
Niceeeee that would be dope.
