### ISSUE TITLE
Add timeline filter options from the tweet card

### ISSUE THREAD

**Issue by githupper** [robertodoering/harpy#532]
**Is your feature request related to a problem? Please describe.**
In order to add new filters into harpy pro, user must always scroll to the top to add into the filter list using the icon. Currently, when I met a new filter word inspired by tweets, I need to jot it down somewhere so that I can add into the time filter after I finished reading all the articles bottom up which is incovenient. 

**Describe the solution you'd like**
Add the option to add in a new filter word using the 3 dot menu (after 'reply', 'open tweet externally', 'copy tweet text' and 'share tweet'

Describe alternatives you've considered
Have the option to parse the text in the tweet via the 3 dot menu like OCR and allow user to choose which word/s to filter out would be great if doable'. This is convenient to reduce any spelling mistakes like names such as 'Djokovic' or other unconventional words that are hard to spell.

**Comment by robertodoering** [comment]
Thanks for the suggestion!
I like the idea of having easy ways to populate the filter, including adding hashtags and mentions to it from the tweet card. I will experiment with it in the future.

For hashtags I was planning to enable muting them globally, but it might make more sense to add them to the filter instead. (#357)

**Comment by githupper** [comment]
Thank you for the quick response!  Some tweets do not have any hashtags so not sure if populating the filter with hashtags would help but I'm open to this idea also so long it improves the app.

Thank you for creating harpy to be open source so discussions like this can happen with community input. Very much appreciated!
