### ISSUE TITLE
Harpy's Download/Preview speed gets slower the lower you are in the timeline

### ISSUE THREAD

**Issue by Malavolence** [robertodoering/harpy#533]
As the title says if you are very far down in your timeline it takes very long for images to load.
This only (as far as I can tell) happens if you don't have the images above loaded already (for example if you just opened the app)
I think either making harpy only load the posts you are currently looking at or adding a option to only automatically load images would help a lot
(sorry for the long text)

**Comment by robertodoering** [comment]
Harpy only loads images that are currently on screen, your position in the timeline shouldn't matter.
Are you sure that images loading is taking a longer time than expected only when you have scrolled down?
Twitter's servers sometimes are slower than usual which can increase load time for image temporarily.

**Comment by ayykiri** [comment]
I'm very sure it was slower, I noticed and checked the normal Twitter and that was fine. Weird

**Comment by dnestico** [comment]
That last comment might explain why ages were taking forever to load in my timeline yesterday and only loaded if I actually stopped scrolling, at one point it even have me an error and wouldn't let me login again until I cleared data. All fixed now though.
