### ISSUE TITLE
upgrade all packages for full support of null-safety

### ISSUE THREAD

**Issue by lucmichalski** [robertodoering/harpy#538]
Hi @robertodoering ,

Hope you are all well ! and happy new year !

I was playing with your great project and one thing that was obvious to me is that you should maybe upgrade all packages for full null-safety support

What do you think about that ?

Cheers,
Luc

**Comment by robertodoering** [comment]
Hey Luc,
thanks and happy new year to you too!

The dependencies have all been upgraded to their null safety version as soon as it was possible, or am I missing something?

**Comment by shiravi433** [comment]
hello bro 
after cloning in flutter show more than 1000 error 
loss some file ?

**Comment by robertodoering** [comment]
@shiravi433 hey bro
You have to run the build_runner to generate the missing files, refer to the readme for more information

**Comment by robertodoering** [comment]
Closing this as harpy and dependencies are making use of sound null safety :)
cc @lucmichalski
