### ISSUE TITLE
Rate limit reached 

### ISSUE THREAD

**Issue by FerasK0** [robertodoering/harpy#539]
Hello!

So basically there's some bug that when i press like it cancels out and show the message below even though i just opened the app after like 5 hours from my last usage.

![20220123_145620.jpg](https://user-images.githubusercontent.com/83197825/150677176-7a1f0b5f-6a3c-4888-9ba2-c088c27c53ae.jpg)

And I'm not a like spammer, maybe I'm not understanding the error message but that's what I got from it.

**Comment by robertodoering** [comment]
See #418
