### ISSUE TITLE
Problem authintication falied

### ISSUE THREAD

**Issue by shiravi433** [robertodoering/harpy#554]
Hi bro : 
After replace api key and secret key to flavor run and run in physical android phone about login for twitter show error authintication failed try again 

Whats problem ? 
Must change code in config-envo.dart about api key and secret key ? 
Or problem about twitter devlopment issue 
Thanks for responsing

**Comment by shiravi433** [comment]
![Screenshot_20220127-182542_gryphon free](https://user-images.githubusercontent.com/84978104/151363169-ff929e9e-badc-4834-8fee-a88709423807.jpg)

**Comment by shiravi433** [comment]
![Uploading 16432883922156881794653556997484.jpg…]()

Replace api key and secret key in env_config.dart ?

**Comment by shiravi433** [comment]
Thanks for awnsering 🙏🙏🙏

I replaced consumer key and secret key to this terminal bust show error authentrication failed try again 

Why show this error

**Comment by robertodoering** [comment]
Have you set up the twitter key correctly?
https://github.com/robertodoering/harpy/wiki/Twitter-key-setup


Make sure that the timezone on your phone is set up correctly, otherwise twitter authentication fails
https://github.com/robertodoering/harpy/wiki/Troubleshooting#unable-to-log-in-login-failed-without-showing-the-login-webview


Do you have any output in the console?

**Comment by realmain** [comment]
Fyi - Looking at the Twitter key setup guide, I noticed that it's outdated because Standalone App is no longer a thing. They are now Projects. 

Also, it doesn't seem to have a `3-legged OAuth` option anymore. I only see `OAuth 2.0` and ` OAuth 1.0a` as the authentication options.

**Comment by robertodoering** [comment]
@realmain 
Thanks for letting me know, I'll update the guide with their new setup.
`3-legged OAuth` is equivalent to `OAuth 1.0a`

@shiravi433
Let me know if you need any help with the setup, I will close this issue for now but feel free to comment

**Comment by shiravi433** [comment]
Thanks bro solved problem , 🙏🙏🙏🙏🙏🙏
