### ISSUE TITLE
Add a way to backup and restore settings

### ISSUE THREAD

**Issue by githupper** [robertodoering/harpy#555]
Currently there is no option to backup and restore harpy pro configuration to another device. This is tedious when user is migrating to another phone or installing to multiple devices. 

This is especially difficult when the source device has a large number of filters set which is the scenario that I am having. 

Although harpy pro currently do not have many variables available user configiration compared to say Twitter or Twidere, the ability to backup and restore will be important down the road as harpy pro gets more and more configurable features.

**Comment by robertodoering** [comment]
Thanks for the suggestion! You are right, especially in the future this will become more and more important.

I'll add this ticket to the backlog.
