### ISSUE TITLE
Implement Twitter broadcasts

### ISSUE THREAD

**Issue by dnestico** [robertodoering/harpy#557]
Please add support to the video player to be able to play twitter live broadcasts. With all the crazy news that's been happening lately here in Canada reporters I follow are going live on twitter by the hour so it would be nice to be able to watch the live streams directly in harpy's video player.

**Comment by robertodoering** [comment]
Unfortunately API endpoints for Twitter broadcasts are not yet available, but once they are it would be nice to add broadcasts to harpy

**Comment by dnestico** [comment]
Ah I see :/
