### ISSUE TITLE
Add NSFW spoiler

### ISSUE THREAD

**Issue by UNordicc** [robertodoering/harpy#559]
Hi! I would like to suggest to add any kind of NSFW spoiler on images that has flagged that. Optionally what kind of NSFW is on image (like on official app).
![Screenshot_20220130_085501.png](https://user-images.githubusercontent.com/73536467/151691557-22f8c1ec-4ed1-4971-bf0d-9513c8dd478b.png)

**Comment by robertodoering** [comment]
Thanks for the suggestion, great idea!
I plan to implement this soon.

**Comment by dnestico** [comment]
Hopefully yours on harpy actually works properly because on the twitter app I have "hide sensitive content" OFF but it still hides/marks "sensitive content" regardless.

**Comment by robertodoering** [comment]
I'm not sure if I can get the setting to from Twitter. I might have to manually add a toggle to always show sensitive content (which I would have enabled by default so it's the same as it is now).

**Comment by dnestico** [comment]
Just wondering, is harpy trying to detect "sensitive media" or is it taking it from Twitter, cuz it likes to mark ALOT of images as "sensitive media" even when they're not.

**Comment by robertodoering** [comment]
We're getting the flag from Twitter.
There are quite a lot of false positives, yeah. It's the same on Twitter web if you disable showing possibly sensitive data.
That's also why the option is disabled in harpy by default.
