### ISSUE TITLE
Notifications push and feature to get notified from the people you specifcally choose to

### ISSUE THREAD

**Issue by NeuronSooup** [robertodoering/harpy#560]
First, thank you so much for creating this. Thanks to people like you, idiots like me can live a happy live in private 
I would like to suggest a feature just like in Twitter, a notify bell next to the following button. I found this really handy in Twitter that I can get the latest tweets and notifications from...say content creators or the account that I receive news from

**Comment by dnestico** [comment]
Soon hopefully #455

**Comment by scottiefalkon** [comment]
I wouldn't think that would include push notifications for individual
accounts you follow. That's a huge ask and quite costly.

**Comment by robertodoering** [comment]
Thanks @NeuronSooup,
as @dnestico mentioned there is already a ticket for push notifications #455, so I will close this one.

I do plan to add notifications for individual users. You'll be able to toggle notifications on / off for specific users that you follow (or even ones that you don't follow) and you'll be notified whenever they have new tweets :)

@scottiefalkon It actually wouldn't be much more difficult than adding push notifications for new tweets in general

**Comment by NeuronSooup** [comment]
@robertodoering thanks
