### ISSUE TITLE
Add scroll to top action for selected home tab

### ISSUE THREAD

**Issue by simanchal-45** [robertodoering/harpy#564]
Title says it all. I didn't like the current arrow icon.

**Comment by dnestico** [comment]
A scrolling animation would be nice too because sometimes it just jumps all the way to the top as of right now for me.

**Comment by robertodoering** [comment]
@dnestico 
It'll jump to the top after a certain amount has been scrolled (about 3 screen-heights).

Animating to the top in 1 second causes too much of the timeline to render in quick succession when you have scrolled to far, which can become too expensive and cause the app to drop frames. So in that case we prefer to jump to the top instead.

**Comment by dnestico** [comment]
Oh
