### ISSUE TITLE
Add tweet card preview in theme customization

### ISSUE THREAD

**Issue by FerasK0** [robertodoering/harpy#569]
Just purchased Harpy pro and I'm excited to the features that about to come, but there's room for improvement.

When making a theme i suggest putting a reference of some kind like a tweet with the different types of color variables below to see the changes in real time instead of depending on trial and error (putting colors than finding the don't match and trying again) :p

My idea is using the same template in the display settings 
vvvvvvv
<img width=250 src=https://user-images.githubusercontent.com/83197825/152742759-e91b56bc-07a0-4b18-a66c-62ee67bd26b6.jpg />

And putting it somewhere here.
vvvvvvv
<img width=250 src=https://user-images.githubusercontent.com/83197825/152742435-4b5f3e13-f475-4a56-afbf-697ec2595af9.jpg />

**Comment by robertodoering** [comment]
It'll be a bit tight but maybe we can have a 'show preview' button to show a tweet card preview.
That would be nice, thanks for the suggestion :)
