### ISSUE TITLE
Change tweet card gesture detection

### ISSUE THREAD

**Issue by FerasK0** [robertodoering/harpy#570]
I noticed a problem but more like a inconvenience, when someone tweets a video or a picture and someone quotes it.

Lets say Person1 tweets a photo, then person2 quotes it, you can't click on the tweet for the person1 and you left with two choices, either going to person1 profile or viewing his photo.

I think the fix is making the profile name and photo (red area) only show the profile, while anywhere else is for the tweet for person1 it self (green area).

![IMG_20220208_092411_595.jpg](https://user-images.githubusercontent.com/83197825/152930193-e6c6073d-1538-418f-a29d-df1f1f71209a.jpg)

**Comment by robertodoering** [comment]
Thanks for reporting the issue and the suggestion! Sounds good to me, will add this to the board.
