### ISSUE TITLE
Saved images do not appear in android's recent media

### ISSUE THREAD

**Issue by Nogooduser** [robertodoering/harpy#574]
## Bug description 

Downloading any image or video works fine, however no matter where I tried to save the files, they never show up in Android's recent files/media browser. 

This isn't system breaking, but it does mean that, for example, if I want to share an image I downloaded from harpy on discord or whatsapp I can't do it easily because it won't show up in my file picker, and I'm sure the same would apply to any software that uses android's recent files. 

Changing the downloaded file's name afterwards makes it show up just fine, and Twitter's official app doesn't run into this issue, so it's something to do with the way harpy is saving the files. 

---
### Expected behavior

Downloaded files should immediately show up in recent media. 

---
### Steps to reproduce

1. Download any image or video
2. Use an app like discord or Whatsapp to send a media file (or just open the default android file browser and check the recent section)
3. There won't be any images or videos from harpy. 
---
Device is a Samsung Galaxy M52 5G running Android 11 and I'm running the pro version of the app. 
I haven't had the chance to test on a non Samsung device so I can't say for sure if it's OEM specific, but I've seen this bug happen in other apps and in other ROMs, so I'm presuming it's not.

**Comment by robertodoering** [comment]
Thanks for reporting the issue! This has been an issue for a while and I recently experimented with the way harpy saves files.
This change add a system notification that you can tap on to open the file and it should fix the issue where your image viewer isn't notified about the new file.
I'll release the fix with the next update :)

**Comment by FerasK0** [comment]
Hi, a bit late and I know it's a work in progress but i just want to ask, isn't there a way to make it a work in the background ?

I don't think a notification to open the file is convenient for someone who saves a lot of media through harpy especially  that it's  a more media oriented client, at least for me.

**Comment by Jimmisama** [comment]
It's saved but not showing up in Google's gallery or files app. Found the saved pictures using third party files manager. In Google's gallery app, rename the folder will force the "previews" to be updated and show up. No other method found yet

**Comment by robertodoering** [comment]
@Jimmisama 
This will be fixed soon with the next update (0.9.0)
