### ISSUE TITLE
Hide notification bar.

### ISSUE THREAD

**Issue by PrithirajN** [robertodoering/harpy#575]
It would be great if the notification bar can be hide while scrolling or completely. It causes overlapping of text.
![Screenshot_20220212_225456~2.jpg](https://user-images.githubusercontent.com/60390549/153721506-03fd1a3f-7316-4c4b-ad3d-0dc797875877.jpg)

**Comment by robertodoering** [comment]
Personally I don't like enabling immersive mode to hide the status bar, but I might consider adding an option for it in the future.
I'll close this issue for now though and keep it it mind going forward.
