### ISSUE TITLE
Add option to automatically translate tweets

### ISSUE THREAD

**Issue by monywoex** [robertodoering/harpy#578]
I suggest adding an automatic translation function. The current translation function is very good, I can click the button in the lower right corner to translate English into Chinese. And it is shown both English and Chinese, it is great. 
Can you add a function to auto translate all tweets in foreign language?I mean there's no need to manually click the translate button one by one.
Thank you very much,Salute to you

**Comment by robertodoering** [comment]
That sounds like a good idea, thanks for the suggestion :)

**Comment by many-fac3d-g0d** [comment]
@robertodoering Can I work on dis feature & also is there any official channel to discuss regarding harpy development ?

**Comment by robertodoering** [comment]
@many-fac3d-g0d
Yes, feel free to add this feature! There is no official channel, you can either ask for advice or any questions here, send me an email or through discord if you want.
