### ISSUE TITLE
Add trending tabs on the homescreen

### ISSUE THREAD

**Issue by eclipseo** [robertodoering/harpy#580]
I'm trying to move away from the abandoned Flamingo Twitter client and one of the features I liked was to add multiple trending pages on the home screen. Could this be implemented?

Thanks.

**Comment by robertodoering** [comment]
Can you clarify what kind of Tweets are visible inside a trending tab on Flamingo?
Does it allow you to follow a specific 'trend' and inside the tab you have popular tweets of that trend?

**Comment by eclipseo** [comment]
Yes, basically, you add a Trend tab, for which you select a location, and it displays the popular tweet of that location.

**Comment by robertodoering** [comment]
You'll be able to set a specific trend as a tab in your home screen with #319, but I don't plan to add popular tweets for a set location as a tab.
