### ISSUE TITLE
Add gif search in tweet composition

### ISSUE THREAD

**Issue by eclipseo** [robertodoering/harpy#581]
When composition a new tweet you should be able to search online services like giphy to include a gif in your tweet.

**Comment by robertodoering** [comment]
Sounds good, thanks for the suggestion

**Comment by dnestico** [comment]
@robertodoering Speaking of GIPHY support, can you allow GIFs to be pasted in to the tweet drawer so that for now I can use GBoard's built in GIF search?

 ![Screenshot_20220218-200300~2.png](https://user-images.githubusercontent.com/3034555/154779721-050f4373-73c6-4fa0-b7f2-f480e752ace2.png)

**Comment by robertodoering** [comment]
@dnestico Flutter still doesn't support this, unfortunately. Once it's possible this should be pretty straight forward to implement

**Comment by dnestico** [comment]
@robertodoering Ah I see! Hope it's on their roadmap or their at least aware of this for the future. Thanks.

**Comment by robertodoering** [comment]
Yeah there are multiple open issues in flutter that I'm following and it seems like progress is being (slowly) made

**Comment by dnestico** [comment]
Nice!
