### ISSUE TITLE
Add reply amount next ro reply symbol

### ISSUE THREAD

**Issue by alxy122** [robertodoering/harpy#592]
Currently it sadly never shows how many replies there are for a reply or the tweet itself. That would be a nice feature to add because I like reading through replies and rn I don't even know if there are any.

Screenshot:
![Screenshot_20220305-210807](https://user-images.githubusercontent.com/83724528/156898503-25626db2-b112-4a91-9232-ae7852409640.jpg)

**Comment by robertodoering** [comment]
#321
