### ISSUE TITLE
Authentication Failed, please try again.

### ISSUE THREAD

**Issue by FerasK0** [robertodoering/harpy#595]
### Bug description 
I entered harpy and was surprised that I was logged out, and tried to log in, I was faced with a toast notification "Authentication Failed, please try again." And it's occurring in the free and pro versions for me.

![Screenshot_20220307-163731_harpy.jpg](https://user-images.githubusercontent.com/83197825/157045758-e78f7e9a-7a1c-4923-b6ac-5920928d42e2.jpg)

---
### Expected behavior
Being forwarded to the Twitter sign-in site

---
### Steps to reproduce

1. Open the app while logged out
2. Click on 'Login with Twitter'
3. See error

---

### What I tried to fix it

1. Deleting cache and data *didn't work*
2. Uninstalling Harpy and reinstalling *didn't work*
3. Checking Twitter "Apps and Sessions" *harpy wasn't on there*
4. Restarting My phone *didn't work*

---

### OS Version

- Android 10
- Samsung Note 9 - Exynos
- February 1 Security Patch
- Harpy Free & Pro 0.8.4

---

**Comment by robertodoering** [comment]
Thanks for the issue.
I had to update the key - a new version in currently being reviewed in the play store.

**Comment by shaurya-src** [comment]
When can we expect to recieve the update?

**Comment by robertodoering** [comment]
It's still 'In Review' in the play store. Unfortunately this can take up to 48 hours sometimes. Hopefully it'll be live very soon.

**Comment by dontobi** [comment]
I just received the update.

**Comment by dnestico** [comment]
Just updated and working.

Also, so I guess this means harpy is officially on the twitter V2 API? 👀

![Screenshot_20220308-174613~2.png](https://user-images.githubusercontent.com/3034555/157339293-3fa193be-49a4-4fc8-b051-b24206f0b987.png)

![Screenshot_20220308-174623~2.png](https://user-images.githubusercontent.com/3034555/157339301-1bf380c5-faf7-4ced-9014-4cd55dc90631.png)

**Comment by robertodoering** [comment]
@dnestico We are using a v2 capable key now, but the app is still using the v1 endpoints.
This now allows us to start implementing v2 endpoints now, though. Such as the v2 'like' endpoint, which has less aggressive rate limiting :)

**Comment by dnestico** [comment]
@robertodoering Nice! Can't wait for it.

**Comment by dnestico** [comment]
Just reported it yup me too.
