### ISSUE TITLE
Show suggestions when we search a user

### ISSUE THREAD

**Issue by simanchal-45** [robertodoering/harpy#599]
Like this⬇️

![Screenshot_2022-03-09-10-25-29-69](https://user-images.githubusercontent.com/71957533/157375653-3b1069f7-d28c-484a-b30e-3cf456519e01.jpg)

**Comment by FerasK0** [comment]
You can see suggestions, you just type and press done.

![Screenshot_20220309-111350_harpy.jpg](https://user-images.githubusercontent.com/83197825/157400080-a5b05daf-1b2e-43f1-8b84-6ed005d655ab.jpg)

I think what you mean is showing them real time as you type which i think is mentioned here: #498

**Comment by simanchal-45** [comment]
Exactly.

**Comment by dnestico** [comment]
Check #498
