### ISSUE TITLE
Unable to display some Unicode characters

### ISSUE THREAD

**Issue by jurichmitchell** [robertodoering/harpy#606]
I'm not sure how many characters in total are affected, but I have found at least one Unicode character that displays as the Replacement Glyph in app.

U+2E2E :  Backwards Question Mark (aka Irony/Sarcasm Punctuation) ⸮

Most probable cause would be the font lacking this character.

**Comment by robertodoering** [comment]
Duplicate of [#495](https://github.com/robertodoering/harpy/issues/495)
