### ISSUE TITLE
Timeline problem with the Android gestures

### ISSUE THREAD

**Issue by dontobi** [robertodoering/harpy#610]
### Bug description 
I use a Pixel 6 (Android 12L) with gesture control. When I execute the gesture to get to the homescreen, I noticed something. When I execute the gesture slowly, the timeline does not scroll in Harpy. However, if I execute the gesture quickly, the timeline scrolls a little bit. See screenshots.

---
### Expected behavior
No matter how fast the gestures are executed, the timeline should not move.

---
### Steps to reproduce
1. Open harpy
2. Quickly perform the gesture to get to the homescreen
3. Open the Task Switcher and see the preview of Harpy

---
### Screenshots
![Screenshot_20220322-083323](https://user-images.githubusercontent.com/19261667/159430199-2aefed9f-92fa-4ad2-8da1-a5229be6f0a0.png)
![Screenshot_20220322-083331](https://user-images.githubusercontent.com/19261667/159430210-c10621cb-d63d-4996-888e-a43f198e0871.png)

---
### Device information
Device: Google Pixel 6
Android: 12L
Build: SP2A.220305.013.A3
Launcher: Nova and Pixel Launcher

**Comment by dnestico** [comment]
Yea I noticed this too whenever I close the app, I have the Pixel 6 Pro.

I normally just go back in to the app and reposition it quickly then reclose slowly or I just leave it since harpy will remember the timeline position anyway which you can set in the settings.

**Comment by robertodoering** [comment]
I have noticed this too. This is an issue with flutter and ideally it'll be fixed on their end but an easy fix in harpy is to prevent vertical gesture detection at the bottom to prevent vertical scrolling during the system navigation.

I've added areas on the side to prevent horizontal gestures and at the bottom to prevent vertical gestures:
<img width=250 src=https://user-images.githubusercontent.com/20045287/159757910-746b00a4-d004-45f4-ac0d-9681d01a0c6a.png />

This should be prevent this issue until it's fixed on flutters side :)
Will be released with the next update (0.9.0)

**Comment by dontobi** [comment]
Thanks for the info. I am very excited about the new version and hope that it will be released soon.

**Comment by dnestico** [comment]
Nice! Excited for this update, hopefully, it drops soon.
