### ISSUE TITLE
Comments on Tweets ends up on my timeline as posts

### ISSUE THREAD

**Issue by ryan7zoom** [robertodoering/harpy#613]
### Bug description 
Whenever I reply to someone's tweet, my comment doesn't show up. Instead, it shows up as one of my Tweets on my profile.

---
### Expected behavior
I was expecting my comment to show up under people's posts.

### Device Info
Android 12, Realme UI3

**Comment by robertodoering** [comment]
This is a side affect from temporarily removing mentions from tweets. The tweet is still a reply to the original one - the @mention is just not present in it.
Will be fixed with the next update (0.9.0)
