### ISSUE TITLE
Android 13 per app language

### ISSUE THREAD

**Issue by dnestico** [robertodoering/harpy#614]
Please make harpy support the upcoming Android 13 "per app language" feature, this would be great so that it would make all tweets in the selected language.

Yes android 13 is far away but still thought I'd add this just so you can see it for the future 👍

https://developer.android.com/about/versions/13/features/app-languages

**Comment by robertodoering** [comment]
Thanks for sharing this! I just checked on an android 13 emulator and this will work out of the box with existing apps (we don't have to explicitly support it).

For harpy Tweets are translated into the system language by default. With this android 13 feature you can change whatever system language harpy will see and use as the default.
You can already set a custom translation language for harpy in the language setting though, so this isn't really that useful.

In the future this will also influence the UI language and you'll also be able to automatically translate Tweets into your target language :)
