### ISSUE TITLE
"Open by default" no Twitter link support 

### ISSUE THREAD

**Issue by Traister101** [robertodoering/harpy#615]
### Bug description 
 Harpy doesn't support opening Twitter links in app. 
 [Screenshot](https://user-images.githubusercontent.com/66151907/161352606-e6a8c836-41c5-44c9-973c-13c7003b2ec0.jpg)

---
### Expected behavior
 Open same links vanilla Twitter [supports](https://user-images.githubusercontent.com/66151907/161352736-b22329cd-532d-475c-b7ec-33f46431d1aa.jpg) ie links that can open in Twitter should open in Harpy

---
### Steps to reproduce

Find valid Twitter link example link https://twitter.com/Twitter/status/1509951255388504066 
Attempt to open the link in harpy

---
 OnePlus 8 running Oxygen os 11 (based on android 11)

**Comment by FerasK0** [comment]
Check #256
