### ISSUE TITLE
Twitter spaces and bookmarks

### ISSUE THREAD

**Issue by patster98** [robertodoering/harpy#624]
The only two things that really make me not leaving official Twitter are bookmarking tweets for reading later and spaces.. it would be great if those were implemented.. any plan on doing so?
Thanks! And great work btw!
Even considering getting the pro version when the app is further developed

**Comment by patster98** [comment]
https://developer.twitter.com/en/docs/twitter-api/spaces/overview

**Comment by dontobi** [comment]
Twitter Spaces:
https://github.com/robertodoering/harpy/discussions/583

**Comment by robertodoering** [comment]
An issue for bookmarks also exist already: #361
