### ISSUE TITLE
Refresh only pulls the last 6h 

### ISSUE THREAD

**Issue by yoshimo** [robertodoering/harpy#635]
### Bug description 
When i open the app and pull in new tweets from my timeline , i only get tweets that were posted in the last 6h.

---
### Expected behavior

I expect to see all tweets between the last refresh and the current date&time.
---

Android 8, Galaxy S7

**Comment by robertodoering** [comment]
I can't replicate this issue. Refreshing the home timeline always fetches the last tweets and doesn't have a 6h time limit.
