### ISSUE TITLE
Sorting the menu elements without function

### ISSUE THREAD

**Issue by dontobi** [robertodoering/harpy#642]
### Bug description 
Sorting the menu items is without function.
I am not able to move the media tap or any other element.
Adding lists works, but they cannot be moved afterwards.

---
### Expected behavior
Sorting via the displayed button should be possible.

---
### Steps to reproduce
1. Open harpy
2. Tap in the settings button
3. Tap in the sorting Icon an try to sort the menu items

---
### Device information
Device: Google Pixel 6
OS: 12L (SP2A.220505.002)
App Version: 0.9.0

**Comment by robertodoering** [comment]
Thanks! Just pushed a fix to master.
