### ISSUE TITLE
Tweets duplication

### ISSUE THREAD

**Issue by FerasK0** [robertodoering/harpy#643]
### Bug description 
If you tweeted, replied to, or quoted a tweet, you will notice that your tweet has duplicated the one before it.
and to fix the bug, you simply just scroll down and back up.

apparently, the bug occurs only with a similar tweet structure, meaning that if you replied to someone, the tweet will only duplicate tweets with a reply. and so on.

My timeline is filled with this bug occurring multiple times and it can not only affect your tweets, it affect other's tweets by taking your context and applying it.

### **Here's an example of a plain tweet:**

![image](https://user-images.githubusercontent.com/83197825/168414905-fccb7eba-784e-43c5-90c9-89f327c59694.png)
_^as you can see my tweet has duplicated^_

![image](https://user-images.githubusercontent.com/83197825/168414945-c143827d-e5df-4f7b-ba04-e408ab15037b.png)
_^and here it is after fixing it by scrolling down then back up^_

### **here's another example:**

![image](https://user-images.githubusercontent.com/83197825/168415111-bc98eaf8-2700-4077-807a-d61bf167f5ee.png)
_^with the bug, *red boxes are the same context, just censored it for privacy*^_

![image](https://user-images.githubusercontent.com/83197825/168415198-8558a7fc-7d97-4eb6-b383-44b3d687ec02.png)
_^without the bug^_

### **here's another example of a replied tweet:**
![image](https://user-images.githubusercontent.com/83197825/168415246-04e40d42-b144-4686-85ae-9d4fe434d4b1.png)
_^with the bug^_

![image](https://user-images.githubusercontent.com/83197825/168415257-cee8a56a-29b7-4a4f-bde2-1405f0cd7a62.png)
_^without the bug^_

---
### Expected behavior
The tweets just appear as expected

---
### Steps to reproduce

1. Compose a tweet
2. Tweet it while another tweet with the same structure is on the screen
3. See error

---
### OS Version.

- Android 12
- Samsung S22 ULTRA - SnapDragon
- May 1 Security Patch
- Harpy Pro 0.9.0

**Comment by robertodoering** [comment]
Thanks, fixed.
