### ISSUE TITLE
Floating compose button disappear after adding/deleting a list

### ISSUE THREAD

**Issue by FerasK0** [robertodoering/harpy#644]
### Bug description 
Floating button disappears even though the option from the settings is enabled.
disabling it and enabling it back won't fix the issue, closing the app will.
The bug occurs when you delete, or add a list.

---
### Expected behavior
The floating compose button shouldn't be effected by adding or deleting lists.

---
### Steps to reproduce

1. Go to app bar settings
2. Either add or delete an added list
3. Go back to timeline

---

### OS Version.

- Android 12
- Samsung S22 ULTRA - SnapDragon
- May 1 Security Patch
- Harpy  Pro 0.9.0

**Comment by robertodoering** [comment]
Nice catch! I just pushed a fix on master.
