### ISSUE TITLE
GIFs downloaded in an unsupported format

### ISSUE THREAD

**Issue by FerasK0** [robertodoering/harpy#645]
### Bug description 
some GIFs if downloaded can't be opened and are viewed as unsupported file type
even though another GIF with the same format is perfectly fine.

![image](https://user-images.githubusercontent.com/83197825/168416411-fdea6b75-d21c-487e-8c5e-7a0f75ac091e.png)
**^GIFs showed in Harpy^**

![image](https://user-images.githubusercontent.com/83197825/168416425-5e0de0c4-73cf-4b13-90f3-cc4270d60af8.png)
**^GIFs showed in Gallary app^**

![image](https://user-images.githubusercontent.com/83197825/168416446-6c2aa3e4-e295-4f4e-9243-2ee096f25fbe.png)
![image](https://user-images.githubusercontent.com/83197825/168416471-be5039b3-315a-42ae-a6b7-77eb648e8775.png)
### **^GIFs info^**

![image](https://user-images.githubusercontent.com/83197825/168416492-68c3bc1f-64e4-4202-b0fa-adb63a2d47f6.png)
**^After trying to play the unsupported GIF through Samsung's media player^**

---
### Expected behavior
Downloaded GIFs are downloaded without any incompatibility issues

---
### Steps to reproduce

1. Download a GIF
2. Check your media app or files app of your choice
3. Open the desired GIF

---
### OS Version.

- Android 12
- Samsung S22 ULTRA - SnapDragon
- May 1 Security Patch
- Harpy Pro 0.9.0

Notes:
I used Samsung's ( Gallary - My Files ) Apps to view the GIFs

**Comment by robertodoering** [comment]
I haven't been able to reproduce this issue on my phone or on an emulator.
If you download the gif again, is it still broken? If yes, can you link me a tweet where the downloaded gif is always broken?
If you open the gif externally, does it play in your browser? And if yes, can you download it from your browser and play it?

**Comment by monee121** [comment]
I have the same issue where the downloaded GIF does not show in Samsung Gallery, and is supported in Samsung Player, but does open and play in Google Photos.

**Comment by FerasK0** [comment]
> If you download the gif again, is it still broken? If yes, can you link me a tweet where the downloaded gif is always broken?

Yes it always comes up corrupted here's the link https://twitter.com/richdifeo/status/1525366402781175808?t=rsSBAvapX6MuG-xSlr-EEw&s=19 


> If you open the gif externally, does it play in your browser? And if yes, can you download it from your browser and play it? 

Didn't try it :p

**Comment by robertodoering** [comment]
The gif works fine for me but I also don't use the Samsung Player. Seems like it's an issue with that so I can't do anything about that for now.

**Comment by FerasK0** [comment]
> The gif works fine for me but I also don't use the Samsung Player. Seems like it's an issue with that so I can't do anything about that for now.

Understood, if i got my hands on another brand phone I'll trying to recreate the issue :)
