### ISSUE TITLE
Floating button

### ISSUE THREAD

**Issue by dontobi** [robertodoering/harpy#648]
### Feature Request
When the floating button is activated, the Compose button at the top should be hidden.

Also, the floating button should be displayed larger and without transparency.

### Device information
Device: Google Pixel 6
OS: 12L (SP2A.220505.002)
App Version: 0.9.0

**Comment by robertodoering** [comment]
Personally i prefer it if the design of the floating compose button matches the other buttons and I also don't think it's necessary for the other compose button to be hidden when you enable the compose button.
I know this is subjective but that's what I'll be going with. Thanks regardless.
