### ISSUE TITLE
Mentions doesnt work

### ISSUE THREAD

**Issue by dontobi** [robertodoering/harpy#649]
### Bug description 
Unfortunately, I was not able to send any tweet with one or more mentions for the last few hours. I always got an error message (see screenshot). 

---
### Expected behavior
The mention function should work again. I am not aware of this problem with any other Twitter app.

---
### Steps to reproduce
1. Tap compose button
2. Write a tweet with mention

---
### Screenshot
![Screenshot_20220514-161210](https://user-images.githubusercontent.com/19261667/168429409-664e751b-1a57-4788-979f-7c8aab9d9f1b.png)

---
### Device Information
Device: Google Pixel 6
OS: 12L (SP2A.220505.002)
App Version: 0.9.0

**Comment by robertodoering** [comment]
Thanks! As the message suggests, this error should only appear when mentioning more that 5 users in 24h that you have no relation to.
I pushed a fix to master.
