### ISSUE TITLE
Can't Like Tweets

### ISSUE THREAD

**Issue by monee121** [robertodoering/harpy#654]
### Bug description 

When clicking the heart icon on a tweet to like it, an error message appears that says "rate limit reached please try again later." Has occurred upon first opening app. 

---
### Expected behavior

The heart icon should fill in and the tweet should be liked. 

---
### Steps to reproduce

1. Open app
2. Click heart under desired tweet
3. Error message will appear

---

Harpy version 0.9.0
Samsung Galaxy S21+
Android 12
One UI 4.1
Android security patch level May 1, 2022

https://user-images.githubusercontent.com/105255608/168594120-2c12162f-6e66-4a3d-b8ad-498de0f7a1c1.mp4

**Comment by robertodoering** [comment]
See #418
