### ISSUE TITLE
videos and photos are not displayed in the feed.

### ISSUE THREAD

**Issue by Valturion** [robertodoering/harpy#677]
### Bug description 

---
### Expected behavior

---
### Steps to reproduce

---

**Comment by Valturion** [comment]
Android 6.1

**Comment by robertodoering** [comment]
Can't reproduce this and I'm not aware of anyone else having the same issue.
Please make sure you can reach Twitter's media server (`pbs.twimg.com`) from your device or check that this wasn't a temporary issue.

I'll close this issue but feel free to comment with steps to reproduce this issue if it persists.
