### ISSUE TITLE
Support right-to-left text directionality when composing a Tweet

### ISSUE THREAD

**Issue by robertodoering** [robertodoering/harpy#680]
The directionality of the compose text field should be determined based the glyphs that the user is typing.

See #656

The implementation requires us to determine the text direction based on the characters (whereas currently we only get the text's language of Tweets and use that to determine the text direction).
With that we can also set the text direction for the user description.

**Comment by FerasK0** [comment]
*Important note*

The layout changes based on 3 conditions:

# 1- Starting with a English Number

And the optimal fix or way for it to be implemented is like how Twitter does it, see below the sample text and photos :)

Text:

1 2 3 انا اتحدث العربية i speak English

**Twitter :**
![Screenshot_20220609-173511_Twitter.png](https://user-images.githubusercontent.com/83197825/172874031-681f173f-d7c3-41e9-a9f2-4784f9c35b63.png)

**Harpy :**
![Screenshot_20220609-173538_harpy free.png](https://user-images.githubusercontent.com/83197825/172874057-9f6badae-6156-47f6-a6fb-781d7a104b8a.png)


# 2- Starting with an Arabic Letter/Word

And it's already mentioned and noted in #656 so check that out. 


# 3- Starting with an Arabic Number

And the optimal fix or way for it to be implemented is like how Twitter does it, see below the sample text and photos :)

Text:

١ ٢ ٣ انا اتحدث العربية i speak English واحد اثنان ثلاثة


**Twitter :**
![Screenshot_20220609-174722_Twitter.png](https://user-images.githubusercontent.com/83197825/172876204-80a4d8be-ca0f-4838-b289-85518484b82f.png)

**Harpy :**
![Screenshot_20220609-174651_harpy free.png](https://user-images.githubusercontent.com/83197825/172876222-1912f6b5-ebb9-4858-abba-092cb5ef1c45.png)

That's what i came up with for the moment, the hashtags are another story for that matter, but generally if the start of a sentence is in Arabic keep it RTL, If it's English keep it LTR. 

except of course for numbers they both should behave the same way when they are followed by an Arabic character which is always RTL.

Also here's a general guide that would maybe help in that regard someway, it'd also help you in the future when you open app translations lol :p

[Fundamentals of Right to Left UI Design for Middle Eastern Languages](https://medium.com/blackboard-design/fundamentals-of-right-to-left-ui-design-for-middle-eastern-languages-afa7663f66ed)

**Comment by robertodoering** [comment]
Thanks! That'll be very helpful
