### ISSUE TITLE
Double tapping on the like button artificially lowers the like count

### ISSUE THREAD

**Issue by AliceGrey** [robertodoering/harpy#685]
---
### Bug description 
-If you accidentally double tap on the like button on a tweet (heart icon) it lowers the like count
-If you repeatedly tap on the like button the like count continues to go down all the way to 0

---
### Expected behavior
-Correct like count to be displayed

---
### Steps to reproduce
Find a tweet on your feed and tap on the like button repeatedly (this needs to be done somewhat quickly)

---
Android 12 - Pixel 4a (5G)

**Comment by FerasK0** [comment]
Weird, i can't replicate the bug...

**Comment by robertodoering** [comment]
Fix will be released with the next update. Thanks for reporting the issue :)
