### ISSUE TITLE
Target of URI doesn't exist: 'layout_preferences.freezed.dart'.

### ISSUE THREAD

**Issue by debpalash** [robertodoering/harpy#693]
Target of URI doesn't exist: 'layout_preferences.freezed.dart'.
Try creating the file referenced by the URI, or Try using a URI for a file that does exist.

part 'auth_preferences.freezed.dart'; also same.

how to fix this?

**Comment by robertodoering** [comment]
https://github.com/robertodoering/harpy/blob/master/README.md#development--setup
