### ISSUE TITLE
Latest beta not keeping position 

### ISSUE THREAD

**Issue by dnestico** [robertodoering/harpy#697]
### Bug description 
The latest beta is not holding my timeline position. 

---
### Expected behavior
When I open the app again it should keep my last spot, instead it jumps straight to top everytime in the latest beta

---
### Steps to reproduce

---

Android 12, Pixel 6 Pro latest security update

**Comment by sboulema** [comment]
Also experiencing this. 

Combined with what I can only describe as: when scrolling in the timeline suddenly it scrolls at hyperspeed and I have to scroll back to where I was.

**Comment by robertodoering** [comment]
Thanks for reporting the issue @dnestico!
A fix is being released and should be available very soon :)

**Comment by dnestico** [comment]
Great, thanks!

**Comment by robertodoering** [comment]
@sboulema 
Please let me know if you still experience that behavior with the latest update. I couldn't reproduce it but I believe it was related to the issue that is now fixed.

**Comment by sboulema** [comment]
Yup it's fixed! Thank you very much!
