### ISSUE TITLE
Bug: Jumpy timeline when navigating above videos

### ISSUE THREAD

**Issue by Nehemoth** [robertodoering/harpy#716]
When you navigate above a video for some reason there's a jump.

This happen only once when the tweets are new.

To reproduce the bug you just have to open your timeline and begin to navigate, when there's a video you will see like a jump above the tweet that contain the video.

Check the [Video bug](https://youtube.com/shorts/IzTqAx95hEo)

**Comment by robertodoering** [comment]
Thanks for the detailed report of the issue! A fix will be released with the next update.
