### ISSUE TITLE
Trying to explore an user profile through media tab crashes my app.

### ISSUE THREAD

**Issue by John147GHN** [robertodoering/harpy#717]
Using a Samsung Tab S6 Lite with paid Harpy 0.9.5, when I explore an user's profile through the media tab, the moment the app needs to load the next "page" (when the loading circle appears), it always crashes. Already tried to clear cache but it was just 1.5MB and it didn't fix it. Any help is appreciated.

EDIT: And just to add, this did not happen as of 3 days ago, since I use twitter to follow artists so I use the media tab A TON.

**Comment by robertodoering** [comment]
Thanks for reporting the issue.
This issue was introduced with the last version. A fix has already been pushed to master and will be released with the next update.

**Comment by John147GHN** [comment]
Thanks! :)
