### ISSUE TITLE
Custom API keys

### ISSUE THREAD

**Issue by nielspeen** [robertodoering/harpy#718]
Please allow Pro users to use custom Twitter API keys. 

This will resolve rate limits for users who use this feature, and also alleviate it for every one else.

**Comment by dnestico** [comment]
Think he already said he will do this in the future actually.

**Comment by robertodoering** [comment]
Yes for sure, this will come soon.
Thanks for the suggestion.

**Comment by Nehemoth** [comment]
This should be a priority. Practically you have to exit the app to interact with a tweet.

**Comment by heyboots** [comment]
absolutely need this, I am chomping at the bit for it. the rate limiting really kills my flow and i'm constantly opening tweets in the browser just so i can like them.

**Comment by dnestico** [comment]
So now that API key is in the app, I JUST got it set up and I haven't gotten any errors so I guess I followed your setup instructions properly lol.

Cuz I'm just curious I was wondering how does it compare to before without the custom API key? Like what are the new rate limits now compared to before? 

Can't wait to finally be able to like all the tweets without the rate limit error lol.

**Comment by robertodoering** [comment]
Nice to hear you got it set up :)
The rate limits that are user based remain the same - e.g you can refresh your timeline 15 times every 15 minutes.
However, app wide limits are now based on your api key. Most importantly this includes the app wide 1000 likes / 24h limit that is shared across every user of your api key.

Basically you'll now be able to like 1000 tweets in a 24 hour window :)
I just wish Twitter didn't have these aggressive rate limits in the first place

**Comment by heyboots** [comment]
I got mine in too, seems to be working the same as the 0.9.7 apk i built (with great effort as I am NOT any kinda dev, just really stubborn) a couple weeks ago with my own API key.

I didn't see at first that the option to add it only seems to be accessible before you log in to Twitter, it wasn't super obvious where the setting was so I thought I was goin a little nuts.

**Comment by dnestico** [comment]
Thanks!

The timeline refresh rate limit is fine for me now that I've gotten used to it, but the new like rate limit will be a game changer!
