### ISSUE TITLE
Black screen after replying to a Tweet

### ISSUE THREAD

**Issue by robsonsobral** [robertodoering/harpy#723]
### Bug description 

After the most recent update, I get a black screen after every reply I send. 

---
### Expected behavior

---
### Steps to reproduce
1. Submit a reply
2. Tap ok

---
Android 12, via LineageOS, on Motorola One Vision

**Comment by robertodoering** [comment]
Thanks for reporting the issue! I've just released a new version containing the fix: 
https://github.com/robertodoering/harpy/releases/tag/0.9.7

It'll be available in the play store shortly.
