### ISSUE TITLE
Add muting retweets for a user

### ISSUE THREAD

**Issue by John147GHN** [robertodoering/harpy#734]
Feature request. I use twitter to follow painters and artists, and while some of them retweet other great artists and that's how I found their amazing work, others just spam trash, but their art is so good that it's not worthy to unfollow them. So I had this idea that when following a user there would be a "Don't show retweets by this user in home timeline" checkmark to unclutter the timeline. I don't how how feasible this would be but this could even expand to "Per follower settings", so we could follow an user's drawings, another user's retweets, etc, etc. 
Thanks your your work in harpy, it's remarkable the amount of features this app has unlike other Twitter clients.

**Comment by robertodoering** [comment]
This would be a nice feature, I agree. When we add muting and blocking users, we can also add an option to just mute the retweets.
Thanks for the suggestion :)

**Comment by H-Tevin** [comment]
Hey, @robertodoering it seems this functionality was missed when #235 was closed in #857. Any possibility we could still get the muting retweets ability?

That and not being able to move the like button to the right side are the only things holding the app back from being perfect, especially now that it's one of the few left working. Thanks!
