### ISSUE TITLE
Content reflow when scrolling from previously saved tweet to top

### ISSUE THREAD

**Issue by Jebeditis** [robertodoering/harpy#735]
### Bug description 

I'm getting an issue where if I open Harpy and scroll up (towards the latest tweet), the focus will "jump up" and lose my current scroll position when it tries to load a tweet where it contains a retweet with an image. I think it might be the height of the image loading in the retweet which is causing the content to get pushed down.

---
### Expected behavior

I should be able to scroll up smoothly without any content reflow.

---
### Steps to reproduce

1. In settings, make sure you have "show latest read tweet" as the "restore home timeline position on app start"
2. Exit out of app and wait until a few tweets accumulate
3. Open Harpy and you should start near the last read tweet
4. Scroll up slowly
5. The focus will jump up losing your current position as you approach a tweet that has a retweet of an image

---

Samsung S20FE
Android 12, One UI 4.1

**Comment by robertodoering** [comment]
Thanks for reporting the issue. Fix will be released with the next update.
