### ISSUE TITLE
Add video duration in thumbnail

### ISSUE THREAD

**Issue by robertodoering** [robertodoering/harpy#744]
From #742

Media data comes with `VideoInfo` object that contains the duration which we can show on the thumbnail to display the duration before loading the video.

**Comment by HikaruIchijyo** [comment]
> From #742
> 
> Media data comes with `VideoInfo` object that contains the duration which we can show on the thumbnail to display the duration before loading the video.


problem with duration font color on video can u chk on that?
![Screenshot_2022-09-08-16-56-57-061_com.robertodoering.harpy.free.jpg](https://user-images.githubusercontent.com/38470944/189116241-50b98fe0-94f3-4a53-8a92-b340a384f9e5.jpg)

**Comment by HikaruIchijyo** [comment]
> Yeah on light backgrounds its hard to see. I've added a black background and it looks much better:
> ![image](https://user-images.githubusercontent.com/20045287/189124520-8f63ef56-e361-45fe-bf4f-859ebcc8a639.png)
> 

got it
