### ISSUE TITLE
Load all author replies when viewing an individual tweet (aka Threads)

### ISSUE THREAD

**Issue by JonathanWolfe** [robertodoering/harpy#748]
There is currently a stacked card view for tweet threads/chains by the same author 

![Screenshot_20220829-225155](https://user-images.githubusercontent.com/1449779/187338246-7a7ac6fc-8ce1-4d23-bb00-c3094c364ee9.png)

However this view isn't triggered if the tweets aren't loaded by the timeline manager (even if the individual tweets are by the same author)

![Screenshot_20220829-225341](https://user-images.githubusercontent.com/1449779/187338195-ddf3ba3a-dee8-46d5-aa72-86654d6d4970.png)

When viewing any individual tweet, Harpy should recursively search for parents and replies from the author and load them in that same stacked card view. 

What to do about replies from all the non-author commenters: Replies to only the originally opened tweet should be shown in the current replies section.

**Comment by robertodoering** [comment]
Right now we recursively load the parents, but we don't add the reply children to the selected tweet.
I agree, it would be nice to have. Thanks for the suggestion.
