### ISSUE TITLE
does this mean v1 non elevated apikey will work?

### ISSUE THREAD

**Issue by debpalash** [robertodoering/harpy#753]
`Added support to set a custom api key`

**Comment by robertodoering** [comment]
Yes, at least for now until we request v2 endpoints in the future.
See https://github.com/robertodoering/harpy/wiki/Twitter-api-key-setup

**Comment by GNS7** [comment]
Now that it's using API V2, is elevated access necessary for it to work?

**Comment by GNS7** [comment]
Ok, thanks for answering! 🙂
