### ISSUE TITLE
Custom Api Key setting missing

### ISSUE THREAD

**Issue by Nehemoth** [robertodoering/harpy#755]
I don't know if it's me or something in the latest code but the latest version which supposedly support the use for custom API Key doesn't have a setting to set this.
 I'd even logout to see it's was something that would be asked on the signing process but it does not.

Thank you.

**Comment by robertodoering** [comment]
You can access it in the login page at the top right.
I should have specified that in the changelog to make it more obvious.

Though there is an issue at the moment where the credentials aren't persisting properly - a fix is already in review and will be published shortly.

<img width=300 src=https://user-images.githubusercontent.com/20045287/189136858-bb948743-d46a-4ed3-928f-52d7d854537d.png />

**Comment by Nehemoth** [comment]
Thank you, will wait.
