### ISSUE TITLE
Galaxy Fold 4 - occasional blurry text

### ISSUE THREAD

**Issue by pengrd** [robertodoering/harpy#761]
Recently switched to a Galaxy Fold4 and started seeing blurry text in several places. Seems to happen on both the main display and the inner display. Font type and font size does not matter. Curious to see if this is an app issue or a device issue, but I haven't seen this issue in other apps.

![Screenshot_20220916_113506_harpy free](https://user-images.githubusercontent.com/8884848/190676856-8f8919fe-677c-4f27-88c1-2eb8ac9a4c13.jpg)

![Screenshot_20220916_114217_harpy free](https://user-images.githubusercontent.com/8884848/190677847-ce555f6f-7c20-497b-a2f0-2b3153cfe7d6.jpg)

![Screenshot_20220916_114337_harpy free](https://user-images.githubusercontent.com/8884848/190678109-d81c1084-dd3d-42fd-99d1-dfe1c85ef8eb.jpg)

![Screenshot_20220916_114657_harpy free](https://user-images.githubusercontent.com/8884848/190678740-1485d7ef-2dd5-44ee-a7a0-e255cb0c0402.jpg)

**Comment by robertodoering** [comment]
I haven't seen or heard of this issue before and I have no way of reproducing it so it's hard to say.
From a quick search it seems there are quite a few Fold 4 users complaining about blurry text it their apps - but it's weird that you are only experiencing that in harpy.

**Comment by jdhalbert** [comment]
Same issue with my Galaxy Fold 4. Not experiencing this in any other apps.

**Comment by jdhalbert** [comment]
> I find that the blurry text is improved when the _Display->Compact layout_ option is turned off, hope this will help to resolve the issue.

That works!
