### ISSUE TITLE
The 'Share tweet' button overlaps with navigation bar

### ISSUE THREAD

**Issue by Cripy-P** [robertodoering/harpy#770]
### Bug description 

When touching the three dots to open a menu in a tweet, the last option (Share tweet) overlaps with the navigation bar of the smartphone, so I can't use it and need to open the tweet with another app in order to share it. (Huawei P20 Lite)

![harp](https://user-images.githubusercontent.com/93873605/192274118-a07daf04-362c-4a48-9b70-9e2785c387a7.jpg)

---

**Comment by robertodoering** [comment]
Seems like it might be device specific as it works properly on aosp and pixel phones.
<img width=300 src="https://user-images.githubusercontent.com/20045287/192604175-297cfee0-8c72-4567-ae7c-2b293c97fe9b.png"/>

What android version is your Huawei P20 Lite on?

**Comment by Patrick-web** [comment]
Would an optional padding setting be a good workaround? I can confirm I have also experienced this on my Huawei.

**Comment by robertodoering** [comment]
@Patrick-web 
What android version are you on?

**Comment by Patrick-web** [comment]
> @Patrick-web 
> What android version are you on?

Version 9
