### ISSUE TITLE
Timeline it's different than official Twitter client

### ISSUE THREAD

**Issue by MitsuhaKitsune** [robertodoering/harpy#777]
### Bug description 

Today I noticed that the timeline of index showed on Harpy, are different than official Twitter client, there are a lot of tweets that aren't showed on Harpy but yes on the official Twitter client.

On my investigation, seems that Harpy didn't show the Tweets liked by my follows, their responses aren't showed too and some Tweets recomended by Twitter based on my likes are missing too.

Didn't know if something are missing, but as I can see, these are the things that make Harpy show minor Tweets than official app.

---
### Expected behavior

The timeline should be the same than official Twitter client (or better), but for now miss a lot of Tweets.

---
### Steps to reproduce

Open Harpy and update the timeline, then go to Twitter client and update too (Twitter client are bad on this than Harpy, you need scroll and update twice times to really stay updated).

If you compare the timelines, are different, Twitter client show more than Harpy.

---

Tested on Android 11 from Google Play build.

**Comment by robertodoering** [comment]
We can only show the reverse chronological timeline and not the algorithmic one that Twitter uses by default.
This means we can't show any of the Tweets that the algorithm thinks are relevant to you and push into your timeline. This is due to limitations by the Twitter api and there is nothing we can do to change it.

**Comment by MitsuhaKitsune** [comment]
Oh, didn't know that :/

Anyways, liked tweets by followed users can retrieved from API, and their responses too, so only the algorritmic recomendations get missed on Harpy with that.

Thanks a lot, I really love the app, it's well designed and the media tab it's perfect for my use.
