### ISSUE TITLE
Add option to start video playback muted

### ISSUE THREAD

**Issue by robertodoering** [robertodoering/harpy#778]
Currently any video played will play with sound. The user should have the option to play videos muted instead.
By default this option should be disabled.

#### Requirements
- Add an option in the media settings
    - "start video playback muted"
- When instantiating the `VideoPlayerNotifier`, set the volume to 0 if this option is enabled

##### Hints
- Options are saved in `media_preferences.dart`
- When creating the `VideoPlayerNotifier` in `video_player_provider.dart`, pass the option to the notifier

**Comment by ashishmohapatra240** [comment]
Hey, I would like to work on this issue!

**Comment by robertodoering** [comment]
@ashishmohapatra240 go for it! Have a look at the [contributing guidelines](https://github.com/robertodoering/harpy/blob/master/CONTRIBUTING.md) and let me know if you have any questions
