### ISSUE TITLE
Open unhandled twitter deeplinks in an external webview

### ISSUE THREAD

**Issue by robertodoering** [robertodoering/harpy#779]
Currently, if a user opens a Twitter url with harpy but harpy does not have a matching path or can't map the url (e.g. a link to a DM) - harpy will just navigate to the home page.

Instead the url should just be opened in an external webview.

#### Requirements & technical information

- In `handle_redirect.dart` we navigate to home if a requested location doesn't exist (line 21).
- Instead use the `launcherProvider` from `url_launcher.dart` to open the path as twitter url in an external webview

**Comment by Dhi13man** [comment]
On it. Please assign.

**Comment by Dhi13man** [comment]
Fixed in PR [#792](https://github.com/robertodoering/harpy/pull/792). Please review and merge if alright.

**Comment by Spyy004** [comment]
Please assign if still open and no one is working on it

**Comment by robertodoering** [comment]
It's closed and has been completed. Forgot to update the issue sry
