### ISSUE TITLE
Get harpy running on iOS

### ISSUE THREAD

**Issue by robertodoering** [robertodoering/harpy#782]
It should be straight forward. Some plugins that are in use might require some setup.

**Comment by dnestico** [comment]
If you get Harpy working on IOS I will 100% tell my friends on twitter about it!

**Comment by AdiAr11** [comment]
Hi, can I try to run this on ios simulator? Will I need access to twitter API?

**Comment by robertodoering** [comment]
@AdiAr11 Access to the twitter API would be beneficial to verify everything is working as expected, yeah. If you don't have a key, write me an email and I can give you test credentials.

**Comment by dnestico** [comment]
Btw any plans for a web app? I would 100% use it.

I just started learning flutter this week and the whole cross platform ability it has is pretty awesome.

**Comment by robertodoering** [comment]
I could see how it runs on web but the intention is not to have fist class support for desktop & web as the current design doesn't work well on it (and updating the ui to better work on it is a big undertaking)

**Comment by dnestico** [comment]
Alright I'd love to help test if you do, but of course don't make it a priority since the UI is already beautiful and runs great on mobile!

**Comment by AdiAr11** [comment]
@robertodoering Sure, Thank you. I'll write you an email.

**Comment by Aryashakya** [comment]
I would like to work on this.

**Comment by AdiAr11** [comment]
@Aryashakya Sure, please give it a go. I'm also trying, been a little busy with work.

**Comment by Aryashakya** [comment]
#801 The default (free) version of Harpy is working on iOS. Could you review it?
