### ISSUE TITLE
Show tweet edit status & editing history

### ISSUE THREAD

**Issue by robertodoering** [robertodoering/harpy#786]
https://developer.twitter.com/en/blog/product-news/2022/supporting-edit-tweet-functionality

We need to show an indication that a tweet has been edited with the ability to see the edit history.

(requires updating twitter_api to include the new field)

**Comment by Ri-2020** [comment]
Hey I am working on flutter, Can you assign me this issue I will add this feature.

**Comment by robertodoering** [comment]
Hey @Ri-2020, thanks but that's not necessary anymore. Read #884
