### ISSUE TITLE
`Open tweet externally` overflow option doesn't work when Harpy is set as the default Twitter client

### ISSUE THREAD

**Issue by mbestavros** [robertodoering/harpy#787]
### Bug description 

On Android, when Harpy is selected as my system default Twitter client, invoking the `Open tweet externally` button in the overflow menu of any tweet does nothing.

One possible thesis is that the system intent to open a Twitter link is being intercepted and "opened" in Harpy, since it's the default client. Since the tweet is already on screen, nothing happens.

The possible fix may be overloading that intent with something to say that the Twitter link should _specifically_ be opened in a browser, and not in the system Twitter app.

Also note that this happens regardless of whether the `Open links externally`
 option in Media settings is enabled or not. 

---
### Expected behavior

When Harpy is set as my system default Twitter client, pressing the "Open tweet externally" button opens the relevant tweet in my system default browser of choice (Chrome, Firefox, Vivaldi, etc).

---
### Steps to reproduce

1. Set Harpy as default Twitter client systemwide in Android settings
2. Find a tweet, click "Open tweet externally" in three-dot overflow menu
3. Nothing happens

---

Harpy version: `0.9.10`
Device: `Pixel 4a 5G`
OS: Android 13 October patch

**Comment by robertodoering** [comment]
Fixed, thanks for reporting the issue.
