### ISSUE TITLE
Support mixed media types in a single Tweet

### ISSUE THREAD

**Issue by TerrorBite** [robertodoering/harpy#796]
The following tweet, displayed in Harpy, shows only a single attached media:

https://twitter.com/RyanLostinTX/status/1577739432337211393

However, the tweet actually contains four media, one of which is a video, and which are all visible when viewed on web.

Replies contain similar examples.

**Comment by robertodoering** [comment]
Since when can you mix media types? 🤯

This'll require some changes in harpy since we make sure that only the previously expected 1 video, 1 gif or up to 4 images are displayed. Thanks for sharing!

**Comment by dnestico** [comment]
@robertodoering They released that feature this week!

Would love to be able to see mixed media tweets in harpy instead of the link, not even tweetdeck supports it at this point.
