### ISSUE TITLE
Bottom toolbar hidden by warning dialog

### ISSUE THREAD

**Issue by robsonsobral** [robertodoering/harpy#813]
When the toolbar is set to bottom, it can get behind the warning dialog.

![Screenshot_20221020-075117.png](https://user-images.githubusercontent.com/931642/196931057-5b19850b-3993-4906-a0e0-74b721a50903.png)

**Comment by robertodoering** [comment]
Thanks!

When displaying a message, we should check if it's displaying in the home page and if the home app bar is displayed at the bottom - if yes add the height of the home app bar as padding to the snackbar.
