### ISSUE TITLE
Display a loading indicator in the in-app webview when loading a page

### ISSUE THREAD

**Issue by robertodoering** [robertodoering/harpy#815]
Currently, opening the in-app webview will just display a white screen when opening a url and will display nothing when navigating inside the webview.
Instead we can make use of the `onProgress` callback to display a loading indicator.

The indicator should be placed above the webview at the top. It should be a `LinearProgressIndicator`.
If the page is fully loaded no indicator should be built.

Bonus:
- See if we can prevent displaying a white page when the page hasn't yet been loaded
- Fade the progress indicator in and out when it shows / hides

**Comment by John-Daniels** [comment]
Hi @robertodoering assign me to this task

**Comment by VexfulNiko** [comment]
@John-Daniels you can create a PR for this task
