### ISSUE TITLE
Option to sort replies by most liked

### ISSUE THREAD

**Issue by dnestico** [robertodoering/harpy#816]
Right now viewing replies on twitter in general, even on the web app isn't the best experience. I've always been hoping twitter would and option to how we want to sort replies to tweets but they ain't doing that it seems.

Right now I think it sorts the latest tweets first but it would be nice to be able to change that and sort it by the "most liked" tweets first instead.

I think getting the replies can be done using "[conversation_id](https://developer.twitter.com/en/docs/twitter-api/conversation-id)", and maybe harpy can work some magic and find a better way to sort them... haha.

**Comment by robertodoering** [comment]
Yes, this will happen automatically when we use the new api to request the replies.
Right now it already sorts by most liked, but the requests that we can get are so limited that it doesn't have a big affect at the moment.

(closing issue as it will be done with #322)
