### ISSUE TITLE
Can't copy text from tweets 

### ISSUE THREAD

**Issue by dnestico** [robertodoering/harpy#817]
Please allow the text in tweets to be copied, Twitter app recently added this for Android. 

![Screenshot_20221025-082746.png](https://user-images.githubusercontent.com/3034555/197773016-aa35e887-0524-4530-b8c8-3bfed2e74d1f.png)

At least there's a workaround on Pixel phones
![Screenshot_20221025-082750.png](https://user-images.githubusercontent.com/3034555/197773030-778e45eb-db45-4fc4-ba8a-3d401f7761a2.png)

**Comment by robertodoering** [comment]
Making the tweet text selectable doesn't work well and causes some issues in flutter.
Additionally it conflicts with the tap gesture on the tweet card, which we could remove but the issues remain, unfortunately.

**Comment by dnestico** [comment]
Alright, not a big deal since my Pixel 6 has the text select feature in the app drawer!
