### ISSUE TITLE
Option to show the most recent tweets first. 

### ISSUE THREAD

**Issue by xCoNDex** [robertodoering/harpy#820]
Currently the main feed appears to deliver tweets in a random way and not in order of publish.

**Comment by robertodoering** [comment]
The timeline already is in (reverse) chronological order.

If any tweet in your timeline is a reply to another tweet in your timeline, then the position of the 
parent tweet is determined by the newest reply.

**Comment by dnestico** [comment]
> If any tweet in your timeline is a reply to another tweet in your timeline, then the position of the

This part right here messes up the timeline sometimes, I do think. Not sure if there would be a way to solve this other then just disabling replies in the home timeline like I did in the past.
