### ISSUE TITLE
Can't customize themes

### ISSUE THREAD

**Issue by Kyle-Mendes** [robertodoering/harpy#823]
### Bug description 

Attempting to update colors on themes is not working for me. I also can't change the name of themes.

---
### Expected behavior

I cma create and update themes!

---
### Steps to reproduce

1. Go to themes
1. Create new
1. Try to change name, doesn't save
1. Try to change colors, doesn't save

---

Android 13, pixel 6 pro, harpy pro.

**Comment by robertodoering** [comment]
A fix will be released with the next update, thanks for reporting the issue!
