### ISSUE TITLE
Timeline position not being held after latest update

### ISSUE THREAD

**Issue by dnestico** [robertodoering/harpy#836]
### Bug description 
After enabling the new 'restore timeline position on refresh" feature it is doing that when I refresh the timeline, but it isn't restoring the timeline position when I close the app then come back to it a few minutes later instead, it jumps to the very top.

I have restore timeline position enabled on both options.

---
### Expected behavior
Timeline position should be restored when app is opened and also on timeline refersh, not just one or the other. 

---
### Steps to reproduce
1. Go to 'settings'
2. Click on 'general'
3. Enable 'restore home timeline position on timeline refresh'
4. Restart app a few minutes later and it will jump go the top

---

Pixel 6 Pro 
Android 13

**Comment by dnestico** [comment]
Update: This seem's to have only happened twice, so it's a rare bug I guess

**Comment by dnestico** [comment]
Thanks for looking into this! It doesn't seem to happen every time I open the app, just sometimes.

also sorry for closing and then reopening the issue 😅

**Comment by robertodoering** [comment]
It turned out that restoring the position failed when the restored Tweet had a quote.
It's fixed now and will be released with the next update :)
