### ISSUE TITLE
Some Image are Missing 

### ISSUE THREAD

**Issue by Solovertical** [robertodoering/harpy#866]
### Bug description 
It's missing some tweet that include image 
Like this
I have checked the whole comment there no tweet of part 2
Harpy

![Screenshot_2022-12-31-19-00-50-895-edit_com robertodoering harpy free](https://user-images.githubusercontent.com/109901807/210138511-9362649f-11eb-439b-b7a4-86a8947ed4d5.jpg)

---
### Expected behavior
It has to look like this including that image to
Source Image-Official Twitter app 

![Screenshot_2022-12-31-19-01-16-829-edit_com twitter android](https://user-images.githubusercontent.com/109901807/210138494-305a0f10-912a-4daa-b27f-c9a16b1569c1.jpg)

---
### Steps to reproduce
Dunno

---
Xiaomi 11i

**Comment by robertodoering** [comment]
Due to limitations with the Twitter API we can't show all replies (especially not when they are older)
We can make an effort to show only the author's replies, this is covered in issue #748.
