### ISSUE TITLE
Wrong number of following / followers

### ISSUE THREAD

**Issue by karkakol** [robertodoering/harpy#874]
### Bug description 

In main page after unfollowing some account number of following does not change
Number is correct only after killing and running app again

---
### Expected behavior
Number of following should be updated after following / unfollowing 

---
### Steps to reproduce
1. In main page tap on following
2. Tap one of followed account
3. Tap on following
4. Tap on left arrow in top right corner
5. Tap on left arrow in top right corner

Following number did not change

---

Version 0.10.1, Android 10

**Comment by robertodoering** [comment]
Please open a discussion for feature requests, instead of an issue
