### ISSUE TITLE
After logout from harpy and trying to sign up I am automaticaly logged in webview

### ISSUE THREAD

**Issue by karkakol** [robertodoering/harpy#876]
### Bug description 

After logout from harpy I am moved to screen with button "login with Twitter"
After tapping on sign up for twitter twitter page is loaded but i see popup with 
title: "Error"
error message: "Oops, sth went wrong. Please try again later"
Next I tap on "ok" button
then I am logged in webview

---
### Expected behavior
I suppose user should be logged out from webview

---
### Steps to reproduce
1. Log in harpy using username and password
2. Log out from harpy
3. Tap on button "login with Twitter"
4. In webview tap on sign up for twitter

Then described error occurs

---
Version 0.10.1, Android 10

**Comment by robertodoering** [comment]
Clicking on the link should open the link outside of harpy in your browser i suppose.
I've opened a ticket here: https://github.com/robertodoering/twitter_webview_auth/issues/1
in favor of this, #876 and #878
