### ISSUE TITLE
Google signIn / signUp button is loading forever

### ISSUE THREAD

**Issue by karkakol** [robertodoering/harpy#877]
### Bug description 
Google signIn / signUp button is loading forever in webview is loading forever ( while AppleId button loads without problem)

---
### Expected behavior
Google signIn / signUp button should be loaded

---
### Steps to reproduce

1. In Splash screen tap on login with Twitter
2. Tap on Sign up for Twitter
optional:  if user is here logged in webview then logout

Google button is loading forever

---
Version 0.10.1, Android 10

**Comment by robertodoering** [comment]
Closed in favor of https://github.com/robertodoering/twitter_webview_auth/issues/1
