### ISSUE TITLE
Sign up / Sign in via AppleID is not possible

### ISSUE THREAD

**Issue by karkakol** [robertodoering/harpy#878]
### Bug description 
Sign up / Sign in via AppleID is not possible, after tapping on AppleID button appears message : 

"Your request failed due to an error. Please try again later" ( this message was translated from polish language, in poland message is "Nie udało sie zrealizować twojej prośby z powodu błędu. Spróbuj ponownie później")

---
### Expected behavior
I suppose user should be able to sign in / up using appleID 

---
### Steps to reproduce
1. In Splash screen tap on login with Twitter
2. Tap on Sign up for Twitter
optional:  if user is here logged in webview then logout
3. Tap on sign in / sign up with AppleID button

Then error message appears

---

Version 0.10.1, Android 10

**Comment by robertodoering** [comment]
Closed in favor of https://github.com/robertodoering/twitter_webview_auth/issues/1
