### ISSUE TITLE
Unable to view profiles

### ISSUE THREAD

**Issue by quarz12** [robertodoering/harpy#879]
I think this video says it all:
https://user-images.githubusercontent.com/64491670/212889717-96d1efb2-486d-4963-9010-0340daff181c.mp4

---

S10e, android 12

**Comment by robertodoering** [comment]
Are you using your own api key?

**Comment by quarz12** [comment]
yes

**Comment by robertodoering** [comment]
Since 0.10 we are using the v2 api endpoints for the user profile (and in future version more parts of the app will be migrated).
Make sure you are using an api key that can request both v2 and v1 endpoints (i.e. elevated access).

**Comment by quarz12** [comment]
I thought I had elevated access. Turns out I had 2 projects and took the key of the one without it -_-
