### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by luckylukz02** [robertodoering/harpy#887]
The app logged me out. I uninstalled the app and reinstalled from the play store.

Getting Authentication failed error after pressing login with twitter but before putting in credentials. 

![Screenshot_20230408-150057_harpy](https://user-images.githubusercontent.com/80491975/230725346-31f7cdd7-201f-44bd-82a2-2fe4410c4273.jpg)

**Comment by monee121** [comment]
Same with me yesterday, I guess we finally got shut down 😔

**Comment by robertodoering** [comment]
As forewarned, harpy can no longer access Twitter's api and has stopped working.

See https://github.com/robertodoering/harpy/discussions/884
