### ISSUE TITLE
Twitter API reverse engineered

### ISSUE THREAD

**Issue by OshekharO** [robertodoering/harpy#888]
Hii how about using reverse engineered Twitter API as official api is now paid to revive the project??

Link: https://pypi.org/project/twitter-api-client/

Hope this client get's revived.

**Comment by robertodoering** [comment]
There are a few reasons why this isn't an option:
- Relying on undocumented api's or scraping content is unreliable and prone to stop working at any point in time. I don't have time to maintain it.
- This particular library is missing many endpoints we'd need for a proper client.
- Third party clients are still officially banned by Twitter. They can and probably would take actions to have them removed from any official store.
