### ISSUE TITLE
build failed after upgrade to latest code

### ISSUE THREAD

**Issue by tangxiangpi** [robertodoering/harpy#894]
after upgrade to https://github.com/robertodoering/harpy/commit/2f008d70ca7c2da1c3ecfdd1af909d0182cf20f5;
It compiled fine on flutter 3.7 before, I don't know what version of flutter you are relying on for this submission.
After upgrading to flutter 3.10 most of the code works fine, but go_router gets an error 'NavigatorObserver' can't be used as a mixin

**Comment by robertodoering** [comment]
Yeah it doesn't compile right now, I'll have to fork go_router in order to get it working again. Will do so in the following days if I get around to it.

**Comment by robertodoering** [comment]
master is building again
