### ISSUE TITLE
User profile page doesn't load: "error loading user"

### ISSUE THREAD

**Issue by ptk8ofbh** [robertodoering/harpy#895]
### Bug description 
When using a custom API key with the Pro version, attempting to view a user page (either by clicking a profile picture or a user name in a tweet) results in a "error loading user" error. This was working prior to the API shutdown when not using a custom key. I realize you're not actively developing this app still, but if this is a quick triage and/or fix, it would be much appreciated! (I also recognize that this may be an issue with Twitter)

![Screenshot_20230605-203502](https://github.com/robertodoering/harpy/assets/613579/bf501c3a-5c6e-4f9b-8c3c-83ace5cc0270)

---
### Expected behavior
Attempting to open a user page shows the user information and timeline.
---
### Steps to reproduce
1. Pro app - add custom API key information and login to app.
2. Attempt to view a user page from either a user name or picture
3. "error loading user" observed.

---
Android 13 (May 2023 security update) - Pixel 7 Pro

**Comment by ptk8ofbh** [comment]
Got it - so when I use a custom API token, is that all using API v1? (i.e. effectively everything in the app will stop working when that shuts down?)

**Comment by robertodoering** [comment]
Yeah exactly. Everything except the profiles are still using the v1 API endpoints in harpy.

**Comment by ptk8ofbh** [comment]
Got it. Well if it's an easy swap to update the API(s) for the user page to V1, I'd certainly appreciate it (as I'm sure others still using the app would as well), but I certainly understand if it's not worth your time, especially given the uncertainty.

Thanks for the replies and insight!

**Comment by robertodoering** [comment]
@ptk8ofbh Is the app still working for your with your custom api key?

**Comment by ptk8ofbh** [comment]
> @ptk8ofbh Is the app still working for your with your custom api key, or did it break since yesterday?

Yes, it's still working as of present (that's how I've been using the app since early April).

**Comment by robertodoering** [comment]
Interesting, mine was also working up until yesterday. Now it seems that I can't access the v1 api endpoints anymore.

Either way I won't be able to update profiles to use the old API, sorry.

**Comment by robertodoering** [comment]
I changed my mind and updated the profile page to work again using a free key that has access to the v1 api.

You can download the apk from the releases page: https://github.com/robertodoering/harpy/releases

**Comment by ptk8ofbh** [comment]
Great, thanks so much!
